### ISSUE TITLE
error to stop server

### ISSUE THREAD

**Issue by ProDash1998** [bensku/Skript#788] opened 2017-08-11 11:54 UTC
`[13:53:24 ERROR]: #!#!
[13:53:24 ERROR]: #!#! [Skript] Severe Error:
[13:53:24 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[13:53:24 ERROR]: #!#!
[13:53:24 ERROR]: #!#! Something went horribly wrong with Skript.
[13:53:24 ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[13:53:24 ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[13:53:24 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:53:24 ERROR]: #!#!
[13:53:24 ERROR]: #!#! Stack trace:
[13:53:24 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[13:53:24 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)
[13:53:24 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:53:24 ERROR]: #!#!
[13:53:24 ERROR]: #!#! Version Information:
[13:53:24 ERROR]: #!#!   Skript: 2.2-dev30b (custom version)
[13:53:24 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[13:53:24 ERROR]: #!#!   Minecraft: 1.12.1
[13:53:24 ERROR]: #!#!   Java: 1.8.0_144 (Java HotSpot(TM) 64-Bit Server VM 25.144-b01)`

**Comment by bensku** [comment] 2017-08-22 14:02
Duplicate of #237.

**Closed by bensku** 2017-08-22 14:02 UTC
