### ISSUE TITLE
<> chars cause error when sending them to console

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#481] opened 2017-04-10 17:25 UTC
Today I tried to use this kind of code:

`command /test:                                                         
	trigger:
		send "These letters cause the error: <>" to console`

... and it causes this strange error:

> [13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! [Skript] Severe Error:
[13:03:43 ERROR]: #!#! Could not load consoleskript.sk
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[13:03:43 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[13:03:43 ERROR]: #!#! and check whether this error has already been reported.
[13:03:43 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[13:03:43 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:03:43 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[13:03:43 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! Stack trace:
[13:03:43 ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[13:03:43 ERROR]: #!#! java.lang.Exception: java.lang.NullPointerException
[13:03:43 ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1215)
[13:03:43 ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1179)
[13:03:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:566)
[13:03:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:269)
[13:03:43 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[13:03:43 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:03:43 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:03:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:03:43 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:03:43 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[13:03:43 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[13:03:43 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:03:43 ERROR]: #!#! Caused by: java.lang.NullPointerException
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! Version Information:
[13:03:43 ERROR]: #!#!   Skript: 2.2-dev26
[13:03:43 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[13:03:43 ERROR]: #!#!   Minecraft: 1.11.2
[13:03:43 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[13:03:43 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! Running CraftBukkit: false
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! Current node: send "These letters cause the error: <>" to console (consoleskript.sk, line 3)
[13:03:43 ERROR]: #!#! Current item: null
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! Thread: Server thread
[13:03:43 ERROR]: #!#!
[13:03:43 ERROR]: #!#! End of Error.
[13:03:43 ERROR]: #!#!

I am running newest spigot and skript.

**Comment by TheBentoBox** [comment] 2017-04-10 17:46
Duplicate of #465, please search before reporting an error to make sure it hasn't been reported already.

**Closed by TheBentoBox** 2017-04-10 17:46 UTC
