### ISSUE TITLE
Dev25 - unbreaking 4 cant be set variables

### ISSUE THREAD

**Issue by cwken10** [bensku/Skript#449] opened 2017-03-29 08:41 UTC
`set {_enchant} to Unbreaking 4`

something strange for setting unbreaking levels then get this error:

[Server thread/WARN]: [Skript] Using an ID instead of an alias is discouraged and will likely not be supported in future versions of Skript anymore. Please replace '4' with e.g. 'cobblestone'.

**Comment by TheLimeGlass** [comment] 2017-03-29 10:26
Enchantments can't be parsed, so that also means you can't define it in a variable.

**Comment by cwken10** [comment] 2017-03-29 13:20
```
				add Fire Protection 5 to {_enchant::*}
				add Protection 5 to {_enchant::*}
				add Unbreaking 4 to {_enchant::*}
				add Luck of the sea 4 to {_enchant::*}
				add Punch 3 to {_enchant::*}
				add Punch 4 to {_enchant::*}
```

these codes works in minecraft 1.9 before, in 1.11 works too, only Unbreaking <number> got some problem

**Comment by Tuke-Nuke** [comment] 2017-03-29 15:04
It's because it is not an expression, it is a type. A type doesn't accept expressions in its name, that's why you have `parsed as %classinfo%`.
So you make it like
```
add "Fire protection %{_level}%" parsed as enchantment type to {_enchant::*}
```
Skript has 2 types for enchantments: `enchantment` and `enchantment type`.
The first one just parse the name of an enchantment like `"Unbreaking" parsed as enchantment` and the second accepts its level as `"Unbreaking 1" parsed as  enchantment type`.
You can use both everywhere (at least in Skript).

**Comment by cwken10** [comment] 2017-03-30 11:18
oh thanks @Tuke-Nuke , anyway ur code works

**Comment by TheBentoBox** [comment] 2017-03-31 01:32
Working as intended IMO per Tuke's note, closing.

**Closed by TheBentoBox** 2017-03-31 01:32 UTC
