### ISSUE TITLE
Inconsistencies in right click events

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#14] opened 2016-03-15 05:56 UTC
I can close my other issue if you'd like. This one will cover more cases.

In general, right click events in the current build don't always as intended. In the list, "non-usable items" will mean those with no right click action, while "usable items" have a right click action (food, blocks, bows, shields, etc). The issues currently present are:

- **Both hands empty**: works as intended
- **Usable item in mainhand, empty offhand**: works as intended
- **Empty mainhand, usable item in offhand**: doesn't trigger click events when using interactable blocks. Example: shield in offhand, right click on a lever - event doesn't trigger.
- **Non-usable item in mainhand, empty offhand**: triggers two entity interaction events. Example: axe in mainhand, empty offhand, right click a mob - triggers two events. Works as intended otherwise.
- **Empty mainhand, non-usable item in offhand**: doesn't trigger right click events when clicking in open air. Doesn't trigger a basic right click event when clicking on entities. Example: axe in offhand, empty mainhand. Right click on nothing - event doesn't trigger. Right click on an entity and listen for overall "on right click" events - event doesn't trigger. "on right click on living entity" triggers, but searching for a generic "on right click" doesn't work in this situation.
- **Non-useable item in mainhand, usable item in offhand**: Triggers two entity right click events, triggers no events when right clicking on interactable blocks. 
- **Usable item in mainhand, nonusable item in offhand**: works as intended

For testing, I was using this code:
```
on right click on living entity:
	send "Clicked on %event-entity%" to player

on right click:
	clicked block is set:
		send "Clicked on %clicked block%"
	else:
		send "Clicked on nothing"
```

For testing, I assumed something was working on intended if it met the following conditions:
- When right clicking on nothing, it would send just "Clicked on nothing", triggering "on right click"
- When right clicking blocks, it would send "Clicked on %clicked block%", including interactable blocks (levers)
- When right clicking entities, it would send "Clicked on %event-entity%" AND "Clicked on nothing", because it should trigger both the entity click events and the generic "on right click" event.

Hope this helps!

**Comment by TheBentoBox** [comment] 2016-03-15 07:00
Further research, when looking through EvtClick. Keep in mind I don't know Java/plugins, as I said before, but it's readable to me.

I see this line:
```
 if (((PlayerInteractEntityEvent) e).getHand() == EquipmentSlot.OFF_HAND && (mainHand == null || mainHand.getType() == Material.AIR))
    return false;
```

By the look of it, this is basically saying to dive out of the event if the event is triggered from the offhand and the main hand is empty, and if it's an entity interaction event. This probably isn't the best, it should trigger an entity interact event as if they player used the offhand item - e.g. if them main hand is empty and diamonds are in my offhand, and I right click on a zombie, it should trigger an "on right click on zombie with diamonds".

Additionally, there's the huge "checkOffHandUse" function. I don't entirely know the reason this exists, or why all these extra checks are being done to dive out of events: 

```
 if ((useOffHand && clickEvent.getHand() == EquipmentSlot.HAND) || (!useOffHand && clickEvent.getHand() == EquipmentSlot.OFF_HAND)) {
 	return false;
}
```

It shouldn't really matter what the situation is in regards to the main hands and off hand and what's in them and what isn't, the event should always trigger like it did in 1.8. I don't know for sure if checkOffHandUse is really needed. As I understand it, within the PlayerInteractEvent and PlayerInteractEntityEvent, you can do event.getHand() to check which hand it is. Then based on which hand it was, it should trigger an event based on that, maybe allow the hand to be checked via "on right click on zombie with diamonds with offhand". This could add "with mainhand", or just be ommitted to trigger no matter which hand did it.

Obviously I don't really know how Spigot's interact events work. If you right click on a creeper with a sword in the main hand and a flint and steel in the off hand, in theory the event should trigger as being triggered by the off hand with the tool as flint and steel. But I imagine Spigot doesn't always work as you'd like :')

**Comment by Pilvinen** [comment] 2016-03-15 10:02
Hopefully this will help some:
http://minecraft.gamepedia.com/Tutorials/Dual_wielding

You can check how the logic is supposed to work from there. It will probably take a moment to implement properly.

**Comment by bensku** [comment] 2016-03-15 10:28
Spigot always throws TWO click events - one with main hand and one with off hand... Due to that, I need to manually check which hand event should be used.

**Comment by UltraFaceguy** [comment] 2016-03-16 17:58
I can confirm that having an offhand item but no mainhand item bypasses on rightclick in dev7b still, if that helps at all. I'm going through and testing lots of interact things as my server relies heavily on skript, I'll let you know if I come up with any more info :x

**Comment by bensku** [comment] 2016-03-16 18:54
Soo, I figured out that Vanilla client won't send any packets if off hand doesn't have usable item and main hand is empty while clicking air. Other things I'm trying to fix currently.

**Comment by Pilvinen** [comment] 2016-03-16 19:00
I believe that has always been the case - unless you are trying to use something like a button for example.

**Comment by TheBentoBox** [comment] 2016-03-16 19:22
Before, right clicking air with anything in hand, even non-usable item, would send a packet. Bensku is saying that having the non-usable in the offhand sends no packet. So you can't have an empty mainhand and non-usable offhand and detect generic right clicks, unfortunately.

**Comment by UltraFaceguy** [comment] 2016-03-16 19:45
That's... completely unacceptable, actually. I almost can't believe it. What the hell are they doing over there...?

**Comment by Pilvinen** [comment] 2016-03-16 21:36
Dev8:

```
on right click on chest or trapped chest:
  cancel event
  send " This chest is locked!" to player
```

1) Hold a torch
2) Right click chest -> This chest is locked!
3) Switch torch to offhand
4) Right click chest -> The chest opens :-(

**Comment by Pilvinen** [comment] 2016-03-16 21:47
Mojang has now been doing this for some time. They've been optimising Minecraft and removing, for example, what they deem as unnecessary packet sending (and extra damage values, etc). I  mean, why send a packet when clicking with something that's not supposed to do anything, right?

**Comment by TheBentoBox** [comment] 2016-03-17 00:17
This seems less like an issue with Mojang/Minecraft and more like an issue with Skript. The fact that you're opening the chest at all means the packet is being sent. The problem is that Skript isn't triggering the "on right click on chest or trapped chest" event in that situation - empty mainhand, usable item in offhand. That's one of the issues I said in the original post, actually.

> Empty mainhand, usable item in offhand: doesn't trigger click events when using interactable blocks. Example: shield in offhand, right click on a lever - event doesn't trigger.

**Comment by bensku** [comment] 2016-03-17 05:47
Hmm, very interesting. I checked the code, and if player has empty main hand, it makes only off hand click event to appear. The thing is... Does Spigot ALWAYS throw off hand click event at all? It seems that there are few exceptions where it doesn't, like opening chests...

**Comment by bensku** [comment] 2016-03-17 07:16
Hotfixed the problem with intractable blocks. Hopefully I got all of them covered.

**Comment by Pilvinen** [comment] 2016-03-17 08:37
Canceling off-hand events now works in dev8b, off-hand handling is still not bug free:

1) Hold torch in off-hand.
2) Hold nothing in main hand.
3) Right click to place torch.

And it fails to place the torch. But definitely a step in the right direction.

IIRC, TheBukor mentioned that he made a pull request for nfells version of Skript where he had fixed off-hand expression. I wonder if that would be of some help in getting this thing finally wrapper up?

**Comment by Pilvinen** [comment] 2016-03-17 15:56
Ah ... dev8b still bypassing cancel event if you hold torch in main hand + sneak and right click.

**Comment by bensku** [comment] 2016-03-19 13:29
Everything mentioned here is now fixed. Please open new issues if something is still bugging.

**Closed by bensku** 2016-03-19 13:29 UTC
Labels: bug
