### ISSUE TITLE
Issue with on teleport event

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#396] opened 2017-02-20 17:20 UTC
I have the following skript with Skellet to try and stop the spectators from teleporting to players. But for some reason, the on teleport event isn't working. I've just tested it by sending these debug messages but it doesn't work at all. Any idea why?

```
on teleport:
	message "&cDebug: &fStage 1 Pass" to player
	if teleport cause is SPECTATE:
		message "&cDebug: &fStage 2 Pass" to player
		if player does not have permission "skript.bypass.spectatorteleport":
			message "&cDebug: &fStage 3 Pass" to player
			cancel event
			message "&cYou cannot use Spectator Gamemode to teleport to players." to player

```

**Comment by TheLimeGlass** [comment] 2017-02-23 01:10
Couldn't replicate the issue
```
on teleport:
	message "&c%teleport cause%" to player
	if teleport cause is SPECTATE:
		broadcast "ye"
```
Skellett 1.8.1b and Skript dev23

**Comment by TheBentoBox** [comment] 2017-02-25 02:34
I also cannot replicate this issue. Are you sure you're using the right version?

**Comment by ZeTioZ** [comment] 2017-02-25 09:36
I have also the same issue, like sometime when I start the server the on teleport event work and sometine not :/

**Comment by whoshenry** [comment] 2017-02-25 13:10
Yes exactly @ZeTioZ, sometimes when I restart the server it works fine and other times it doesn't. So it must be an issue on startup.

**Comment by TheBentoBox** [comment] 2017-02-25 14:25
What server version are you guys on? (Just run /ver and send a screenshot here).

**Comment by ZeTioZ** [comment] 2017-02-25 19:18
@whoshenry look, I build a code to know if the on teleport event work as well.

`command /tpfix [<text=off>]:
	permission: fixer.admin
	permission message: &cYou don't have the permission to do that !
	trigger:
		if executor is console:
			if arg 1 is "off":
				if {checkfix.1} is 2:
					send "&cThe checker is disabled !" to console
				else:
					set {checkfix.1} to 2
					send "&2You have disabled the On teleport event checker !" to console
			else if arg 1 is "on":
				if {checkfix.1} is not set:
					send "&cThe checker is already enabled !" to console
				else:
					clear {checkfix.1}
					send "&2You have enabled the Tp-Checker !" to console
		else if executor is a player:
			if arg 1 is "off":
				if {checkfix.1} is 2:
					send "&cThe checker is already disabled !" to player
				else:
					set {checkfix.1} to 2
					send "&2You have disabled the event checker !" to player
			else if arg 1 is "on":
				if {checkfix.1} is not set:
					send "&cThe checker is already enabled !" to player
				else:
					clear {checkfix.1}
					send "&2You have enabled the event checker !" to player
on join:
	wait 7 seconds
	if {checkfix.1} is 1:
		set {checkfix.1} to 2
		broadcast "[&aTP-Fixer&f] &eOn Teleport event is working as well !"
		stop trigger
	else if {checkfix.1} is 2:
		stop trigger
	else:
		broadcast "[&aTpEvent&f] &cThe On Teleport event is not working."
		broadcast "[&aTpEvent&f] &cPlease, contact a staff member or execute the command &d/tpfix &cto disable the On Teleport event checker."
on load:
	clear {checkfix.1}
	send "[&aTpEvent&f] &eOn Teleport event check enabled !" to console
on unload:
	clear {checkfix.1}
	send "[&aTpEvent&f] &eOn Teleport event check disabled !" to console
on teleport:
	if {checkfix.1} is not set:
		set {checkfix.1} to 1
		send "[&aTpEvent&f] &eOn Teleport event is working !" to console






























#Coded and developped by ZeTioZ© for OpsyNetwork`

**Comment by whoshenry** [comment] 2017-02-25 21:55
My version - This server is running CraftBukkit version git-Spigot-65a0347-1a71021 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Just been testing it again, it works sometimes when I restart and sometimes not, I can't see an error in the log and when I try and reload the script, it doesn't even work then when it failed to load on startup.

**Comment by TheBentoBox** [comment] 2017-12-07 16:10
Is anyone still experiencing this? If not I'll close it soon.

**Comment by Snow-Pyon** [comment] 2018-01-07 07:54
No response and I can't reproduce it, closing.

**Closed by Snow-Pyon** 2018-01-07 07:54 UTC

**Comment by oskarkk** [comment] 2022-02-19 12:13
I've had this problem for at least a year, and I just found out that if you were using SkQuery, this may have been caused by using `on any movement` event. Maybe the root cause is some bug in Skript, not in a particular addon.
