### ISSUE TITLE
Log Handlers

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#1108] opened 2018-02-11 03:48 UTC
Hey!
I've found this in my console together with the issue, that I'm not able to execute ingame Skript expressions.

[04:41:40 ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by bensku** [comment] 2018-02-11 11:07
Is there anything else in console? Other errors?

**Comment by GermanMinerDE** [comment] 2018-02-11 12:55
There is something, but in my opinion not in a temporal context.



[13:48:07 INFO]: SchmidtMax issued server command: /skript reload 08-c-biz
[13:48:29 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! [Skript] Severe Error:
[13:48:30 ERROR]: #!#! Unexpected error while executing effect command 'broadcast "%TausenderTrenner(100)%"' by 'SchmidtMax'
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Something went horribly wrong with Skript.
[13:48:30 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:48:30 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:48:30 ERROR]: #!#! Here is full list of them:
[13:48:30 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction GMAddon (www.GermanMiner.de) WolvSK MundoSK (https://forums.skunity.com/resources/mundosk.69/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK ExertSK skript-mirror skDragon SkStuff skUtilities (https://tim740.github.io/) ExtrasSK SkQuery Ersatz Umbaska PirateSK
[13:48:30 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:48:30 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:48:30 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:48:30 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:48:30 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:48:30 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[13:48:30 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Stack trace:
[13:48:30 ERROR]: #!#! java.lang.NullPointerException
[13:48:30 ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:173)
[13:48:30 ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:164)
[13:48:30 ERROR]: #!#!     at ch.njol.skript.Skript.info(Skript.java:1182)
[13:48:30 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:273)
[13:48:30 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:207)
[13:48:30 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[13:48:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:85)
[13:48:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[13:48:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[13:48:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:48:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:48:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:48:30 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Version Information:
[13:48:30 ERROR]: #!#!   Skript: 2.2-dev32d
[13:48:30 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:48:30 ERROR]: #!#!   Minecraft: 1.12.2
[13:48:30 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[13:48:30 ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Running CraftBukkit: false
[13:48:30 ERROR]: #!#! Running Spigot (or compatible): true
[13:48:30 ERROR]: #!#! Running Paper (or compatible): false
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Current node: null
[13:48:30 ERROR]: #!#! Current item: null
[13:48:30 ERROR]: #!#! Thread: Server thread
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! Language: english
[13:48:30 ERROR]: #!#! Link parse mode: DISABLED
[13:48:30 ERROR]: #!#!
[13:48:30 ERROR]: #!#! End of Error.
[13:48:30 ERROR]: #!#!
[13:50:09 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[13:51:52 INFO]: SchmidtMax issued server command: /skript reload 08-c-biz
[13:52:29 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]



[12:09:26] [pool-76-thread-2/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[12:09:36] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[12:09:46] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by bensku** [comment] 2018-02-11 18:20
It seems that an addon is breaking stuff. Try removing all addons and check if it is still happens. If not, bring them back one by one until issue occurs again and report to addon author.

If removing addons does not fix the issue, please post your Spigot version here and I'll take a look.

**Comment by Snow-Pyon** [comment] 2018-02-20 23:33
Still happening?

**Comment by GermanMinerDE** [comment] 2018-03-08 23:43
Still found something out here: It is happening in sometimes, when a Skript uses the "$ thread" expression for async.

**Comment by Snow-Pyon** [comment] 2018-03-09 02:05
@GermanMinerDE that isn't an expression of Skript though, it's from skQuery. If you can't reproduce it without addons I'm closing this.

**Comment by GermanMinerDE** [comment] 2018-03-09 02:06
Hi - in this case I think, you can close it. Additionally it should be thought about, how some things don't work and something is a little bit weird (like variables not local to the trigger) that eventually refer to this.

**Closed** 2018-03-09 02:45 UTC
Labels: invalid
