### ISSUE TITLE
Links no longer clickable when using latest Skript version with Json fixes

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#543] opened 2017-05-02 16:04 UTC
Players are unable to click on any links in minecraft chat when using latest skript version.
Had to remove skript and replace it with older version of skript to make it work again.

Also players are unable to click on any betonquest answer of NPCs. Looks like similar issue here.

**Comment by TheBentoBox** [comment] 2017-05-02 16:07
@bensku The problem is that links currently **must** start with `https://` for it to parse them as a link (according to the dev26f release notes), even though vanilla by default tries to parse basically anyone word containing a period as a link, e.g. saying "hey.how are you?" would try to parse "hey.how" as a URL. Even though it means some non-links will be registered as links, it's completely harmless and ensures that you don't have to have a full complete URL for it to parse (e.g. I can just say "go to github.com" and it'd work).

I'd recommend changing the URL parsing to happen for every word where a contains check for "." returns true as opposed to checking the beginning of the message for "https://".

**Comment by Snow-Pyon** [comment] 2017-05-02 20:01
@TheBentoBox it just parse links with http:// or https://, not everything with a dot.

**Comment by TheBentoBox** [comment] 2017-05-02 20:56
@Snow-Pyon In vanilla you're correct, but otherwise you're not. This is a test in dev25 of me sending a URL without http[s]:// and it works:

![image](https://cloud.githubusercontent.com/assets/6902229/25638944/1d2374b2-2f58-11e7-9924-05780182fbf7.png)

And it even works on URLs that don't have valid extensions like .com, .gov, etc.:

![image](https://cloud.githubusercontent.com/assets/6902229/25639002/50f39a1a-2f58-11e7-9268-629f0a47bc2e.png)

That being the case, it should still work like this in dev26 too.

**Comment by bensku** [comment] 2017-05-03 08:12
Ouch, time to rewrite link parsing once again... At least it should be relative simple.

**Comment by bensku** [comment] 2017-05-03 13:44
I have resolved this problem (will be in next build). Now, there are three possible link parsing modes:

* Disabled: doesn't parse links
* Strict: parses links which have correct protocol at start
* Lenient: parses anything which contains a dot as potential link and assumes the protocol is just HTTP

**Comment by TheBentoBox** [comment] 2017-05-03 14:09
Nice implementation, you're a legend

**Closed** 2017-05-10 18:48 UTC
Labels: bug
