### ISSUE TITLE
damage cause and attacker are bugged

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#16] opened 2016-03-16 21:22 UTC
This bug has been in Skript for a long time: The %damage cause% and %attacker% are giving out wrong information when damaging the player by code. 

**Steps to reproduce:**

1) Hit player, burn him or generally take damage from something.
2) 
```
command /damageplayer <player>:
  trigger:
    damage arg 1 by 999

on death:
  broadcast " DEBUG: damage cause: %damage cause%, attacker: %attacker%"  
```

3) The damage cause and attacker will now be the last source of damage received **before** damaging the victim with /damageplayer command.

This is not nice for example if you have a skript which keeps track of who or what killed whom. The information will be wildly inaccurate.

Perhaps the ideal fix for this would be simply removing the reference to damage cause + attacker when using the damage expression or setting the damage cause to "magic" when giving damage with code and removing the value of the attacker or setting it to unknown (I don't how it works) - or even better, if possible, making it possible to define the damage cause and attacker.

**Example of what the new syntax might be like:**
damage %entity% by %integer% [heart|s] [[set] cause [to] "%damage cause%" [[set] attacker [to]] %entity%]

**Comment by bensku** [comment] 2016-03-24 18:38
Fixed in next build, kinda of. Dealing damage now correctly sets damage cause, and you can even kinda set your custom one:
<code>damage entity by {_damage} with fake cause {_damagecause}</code>
The cause is "fake" because it is applied AFTER event has passed due to Spigot limitations. That might cause problems, but it is best I can do without NMS code.

Also, you can now modify and/or get last damage cause:
<code>last damage cause of %livingentities%</code>

**Closed by bensku** 2016-03-24 18:38 UTC
Labels: bug, investigating
