### ISSUE TITLE
Too many chat issues in dev26f

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#533] opened 2017-04-25 11:37 UTC
A color code can't clear format codes before it

![image](https://cloud.githubusercontent.com/assets/19474570/25383403/42072bd0-29bc-11e7-9530-0d1f8340c0d1.png)

**Comment by bensku** [comment] 2017-04-27 05:06
Duplicate of #528.

**Closed by bensku** 2017-04-27 05:06 UTC
