### ISSUE TITLE
[Important] Variables from other files are not saved.

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#840] opened 2017-09-03 17:10 UTC
This is a quite important bug I found by using my shop script.

```
databases:
	iShop:
		type: CSV
		pattern: !s.*
		file: ./plugins/Skript/shops.csv
		backup interval: 1 day
	Locations:
		type: CSV
		pattern: l_.*
		file: ./plugins/Skript/locations.csv
		backup interval: 0
	Temp:
		type: CSV
		pattern: .*
		file: ./plugins/Skript/tempdb.csv
		backup interval: 0
```

iShop and Locations are simply not saved.
I lose everything upon every restart.

Test command example:
```
command /lulz:
	trigger:
		loop 500 times:
			set {!s::anything::%random 8 char string from `a-z`%} to loop-number
```

Sometimes they are saved (correctly, no problems) but deleted after restart.

I really need these variables working for my shop script..

Hope you can fix it.
Thanks!

**Comment by bensku** [comment] 2017-09-03 19:33
Duplicate of #457.

**Closed by bensku** 2017-09-03 19:33 UTC
