### ISSUE TITLE
reporting a bug in 1.11 skript

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#244] opened 2016-11-19 02:41 UTC
every 60 seconds:
    loop all players:
        if loop-player is online:
            add 1 to {online::%loop-player%}
            if {online::%loop-player%} is more than 59:
                execute command "/scoreboard players add %loop-player% onlinetime 1"
                set {online::%loop-player%} to 0

worked earlier, now throws:

[Skript] Using an ID instead of an alias is discouraged and will likely not be supported in future versions of Skript anymore. Please replace '1' with e.g. 'stone'. (tablist.sk, line 8: add 1 to {online::%loop-player%}')
[21:40:45 WARN]: [Skript] Using an ID instead of an alias is discouraged and will likely not be supported in future versions of Skript anymore. Please replace '59' with e.g. 'crops'. (tablist.sk, line 9: if {online::%loop-player%} is more than 59:')
[21:40:45 WARN]: [Skript] Using an ID instead of an alias is discouraged and will likely not be supported in future versions of Skript anymore. Please replace '0' with e.g. 'air'. (tablist.sk, line 11: set {online::%loop-player%} to 0')

just so you know

**Comment by PugaBear** [comment] 2016-11-19 02:58
Duplicate of #239

**Comment by bensku** [comment] 2016-11-20 14:11
Not duplicate. But I haven't been able to reproduce this, anyway...

1. Add single Skript which contains what you posted (indentation fixed)
2. Run
3. Command is ran every 60 seconds, players are looped, and command seems to be correctly formatted

@melinstagibson What addons are you using?

**Closed** 2017-08-25 13:10 UTC
Labels: new-parser
