### ISSUE TITLE
var error

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#1208] opened 2018-04-23 13:20 UTC
Skript v2.2-dev34

**loop 2 times:
	make a gui slot {_b1::1} of {_p} with {v.vip.menu.item::%loop-number%} named "§f✔§b%{v.server.tag.%{_b::5}%::%loop-number%}%  %{_b1::3}%"**

[21:41:39 ERROR]: '::%loop-number%}' is not a valid item data (+b.sk, line 839: make a gui slot {_b1::1} of {_p} with {v.vip.menu.item::%loop-number%} named "§f✔§b%{v.server.tag.%{_b::5}%::%loop-number%}%  %{_b1::3}%"')

Then I changed the code
**make a gui slot {_b1::1} of {_p} with ice named "§f✔§b%{v.server.tag.%{_b::5}%::%loop-number%}%  %{_b1::3}%"**

or 

**make a gui slot {_b1::1} of {_p} with {v.vip.menu.item::%loop-number%}  parsed as itemtype named "§f✔§b%{v.server.tag.%{_b::5}%::%loop-number%}%  %{_b1::3}%"**

[21:43:50 INFO]: [Skript] Reloading the config and all scripts...
[21:43:50 INFO]: Loaded a total of 20377 english aliases
[21:43:50 INFO]: All scripts loaded without errors.
[21:43:50 INFO]: Loaded 1 script with a total of 11 triggers and 1 command in 0.3 seconds
[21:43:50 INFO]: [Skript] Successfully reloaded the config and all scripts.

**Comment by Snow-Pyon** [comment] 2018-04-23 14:29
Duplicate of #1138.

**Closed by Snow-Pyon** 2018-04-23 14:29 UTC
