### ISSUE TITLE
error on join dev18b

### ISSUE THREAD

**Issue by Karrade** [bensku/Skript#143] opened 2016-07-29 14:52 UTC
ok i have dev18b and this error is coming up when someone joins the server i believe it has to do with skript itself

`
29.07 10:50:30 [Server] ERROR #!#! 
29.07 10:50:30 [Server] ERROR #!#! [Skript] Severe Error:
29.07 10:50:30 [Server] ERROR #!#! 
29.07 10:50:30 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
29.07 10:50:30 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
29.07 10:50:30 [Server] ERROR #!#! and check whether this error has already been reported.
29.07 10:50:30 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
29.07 10:50:30 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
29.07 10:50:30 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
29.07 10:50:30 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
29.07 10:50:30 [Server] ERROR #!#! 

29.07 10:50:30 [Server] ERROR #!#! Stack trace:
29.07 10:50:30 [Server] ERROR #!#! java.lang.NullPointerException
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.expressions.ExprIP.convert(ExprIP.java:52)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.expressions.ExprIP.convert(ExprIP.java:1)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.getAll(VariableString.java:493)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.check(VariableString.java:503)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondIsBanned.check(CondIsBanned.java:76)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
29.07 10:50:30 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
`

**Comment by bensku** [comment] 2016-07-29 19:39
What are you doing with expression "ip"?

**Comment by Karrade** [comment] 2016-07-29 20:45
`on join:
	if player has permission "banman.update":
		if text from "https://bitbucket.org/karrade0218/ban-manager/raw/master/version.txt" is not "{@Version}":
			wait 3 seconds
			send "{@Prefix} Ban Manager is out of date! Please use &e/banman update &7to automatically update the plugin." to player

	if {banman.tempban.%player%} is true:
		if difference between now and {banman.tempban.timenow.%player%} is less than {banman.tempban.time.%player%}:
			set {_banleft} to difference between {banman.tempban.timenow.%player%} and now
			set {_banleft} to difference between {_banleft} and {banman.tempban.time.%player%}
			kick the player due to "&7Banned by: &c%{banman.tempban.by.%player%}% &7For: &c%{banman.tempban.time.%player%}% &7Time Served: &c%{_banleft}%  &7Reason: &c%{banman.tempban.reason.%player%}%"
		else:
			set {banman.tempban.%player%} to false
	else:
		remove "%player%" from {banman.banlist::*}

	if {banman.ipalts.%IP of player%::%player%} is set:
		stop
	else:
		set {banman.ipalts.%IP of player%::%player%} to player`

**Comment by bensku** [comment] 2016-07-30 07:48
Interesting... This needs some debugging, no idea wjy it is broken.

**Comment by bensku** [comment] 2016-08-14 13:35
Cannot reproduce. Used your code, joined my server -> no errors. I also tested ip expression using <code>!broadcast "%ip of me%"</code> which worked.

Closing this now.

**Closed by bensku** 2016-08-14 13:35 UTC
Labels: bug
