### ISSUE TITLE
Skript had a head injury. [Serious]

### ISSUE THREAD

**Issue by Pugabyte** [bensku/Skript#239] opened 2016-11-17 20:02 UTC
[Skript] [make player execute command "/gl"] is not a valid lambda statement. (-grapple.sk, line 30: set {grapple::gamemode::%shooter%} to gamemode of shooter')
    [Skript] The expression 'argument' can only be used within a command (-AFKHolo.sk, line 88: broadcast "{@logo} {@nafk}"')
    [Skript] [make player execute command "/creative"] is not a valid lambda statement. (sklist.sk, line 140: set {_trusteds::%{_trusteds}%} to "&e%loop-player%"')
    And so on for hundreds of lines...
These errors make no sense....it's even loading disabled scripts, it's erroring on things that don't even exist inside that script (`/creative` is in `creative.sk`, not `sklist.sk`), I can't even...comprehend 99% of these errors.

Im running the latest release (1.11), latest spigot build.

**Comment by bensku** [comment] 2016-11-17 20:34
It doesn't make sense for me either. Interesting...

I'd need to see the event handler or function which has <code>make player execute command "/gl"</code>. As said, this release is considered mostly for testing for a good reason.

**Comment by PugaBear** [comment] 2016-11-17 20:43
I dont think I got the point across that there is no pattern... http://paste.bn-mc.net/exihu

**Comment by Wasabules** [comment] 2016-11-17 22:17
I have exactly same problem.

**Comment by TheBentoBox** [comment] 2016-11-18 00:28
Same issue here, I got literally hundreds of errors on reload, many similar to those above, errors in situations that don't make sense presumably as a result of the multithreaded parser. Probably a good 300+ times of it telling me to use an alias instead of an ID even though I'm not referencing and ID (it thinks numbers are meant to be material IDs half the time), and it'll send the error literally tens or hundreds of times for the same line, e.g. [this](https://gyazo.com/33c9bb706b123538f861488bb0e8503f).

It *does* enable on 1.11 right now, but that's about all it does. Nothing past that seems to work.

Lemme know if you want any more info, good luck with everything! I understand the new parser on top of an update is probably making things very difficult.

**Comment by bensku** [comment] 2016-11-18 07:52
Hmm... Maybe I just use too small script set on test server. Need to write something, I guess.

**Comment by Ekzim** [comment] 2016-11-18 08:11
This also happens to me as well.

**Comment by mmagoo13** [comment] 2016-11-18 19:02
I also get somthing similar  http://pastebin.com/5tsaEX7L . this happens each time i reload my server and none of the commands in my skripts work

**Comment by PugaBear** [comment] 2016-11-18 19:55
Maybe you could apply the 1.11 patch to a release before the start of the multi-threaded parser so we could get going with 1.11, and work on fixing it after?

**Comment by Legoman99573** [comment] 2016-11-19 04:49
in GUI screen, i get an error when it has this in it.
`format slot 22 of player with book named "&aCountry" with lore "&eNot Set" to close then run [make player execute command "profile country"]`

and executes this error
`[22:44:24] [pool-15-thread-6/ERROR]: [Skript] [make player execute command "profile country"] is not a valid lambda statement.`
Worked in 1.9/1.10 at the time.

**Comment by bensku** [comment] 2016-11-19 08:02
I could do 1.11 patch to dev20... I'll consider if it takes more than few days to fix this error with numbers.

Somehow, Skript seems to ignore parsing order of types.  For example, it should parse a number out of number given as function parameter, but instead, it parses entity type or item type.

**Comment by bensku** [comment] 2016-11-20 14:12
Lambdas are SkQuery feature. So is format slot, as far as I know. Please test if <code>make player execute "command</code> works **without** SkQuery or **any** addons.

**Comment by PugaBear** [comment] 2016-11-20 17:32
Its more than make player execute command. The multithreaded parser completely breaks everything.

**Comment by TheBentoBox** [comment] 2016-11-20 18:42
I can confirm that without addons, everything seems to work fine. I have my AdminChat script running fine on 1.11 as it uses entirely vanilla Skript features. I can also use the `make player execute` effect fine on 1.11 when I don't have addons installed. It seems like the parser IS actually working fine in theory, but addons destroy it for whatever reason.

**Comment by Legoman99573** [comment] 2016-11-20 19:05
Couldnt you just implement skQuery into skript since there seems to be no more updates to it.

**Comment by PugaBear** [comment] 2016-11-20 19:52
I'm unable to test at the moment- if you add any addons at all, it breaks? No matter which one?

**Comment by bensku** [comment] 2016-11-21 10:15
It is not likely that just adding an addon breaks everything. More like some features added by addons break stuff.

**Comment by TheBentoBox** [comment] 2016-11-24 19:48
I am now getting some strange issues even without using addons, throwing errors on basic `if` statements. On dev22 (though `/ver Skript` still shows dev21c in game), running a completely fresh (20 minutes old) Spigot 1.11 jar. 

- [My plugins](https://gyazo.com/4b99d891e4d22ca2f675c4d5773ada75) (Note, no Skript addons)
- [Error on reload](https://gyazo.com/930f6564926326fd56e0d3010f2758a5)

The first error is an inline `if` ([the middle line here](https://gyazo.com/c89db505fbd4d83aaf4eed3ecdc75348)). The others are on just normal `if` statements checking if a variable is set to true.

**Comment by Ekzim** [comment] 2016-11-25 05:37
@bensku 
I tried the latest Skript version that was just updated the 1.11 bug fixes and I still have issues.  I don't use any other Skript addons, like SkUtility.  I just run normal java plugins + your version of Skript bensku.  Here is a pastebin of my start up with the latest build of Spigot and the newest Skript dev release.  Lots of errors still, although I know you're still aware of list variables not being handled correctly, there is more than just that.  If you'd like any of the skripts, I can send them to you.

http://www.pastebin.com/KRWbkLhu

**Comment by bensku** [comment] 2016-11-25 12:19
This is interesting... Personally I always use if before condition statement, so might have forgotten to test this.

**Comment by PugaBear** [comment] 2016-11-26 06:30
@bensku There is nothing missing in that screenshot- you can see how it wraps.

**Comment by bensku** [comment] 2016-11-27 12:53
@TheBentoBox Your issue should be fixed now. Same goes for *some* issues @Ekzim had, but I'm not sure if everything was fixed. Weird errors.

**Comment by PugaBear** [comment] 2016-11-27 13:42
But still no progress with addons, @bensku?

**Comment by TheBentoBox** [comment] 2016-11-27 17:53
I'm still getting some issues with simple scripts, but they don't even show up in game anymore, it only throws the errors on console. All of the parsing debug messages are left in, too (not that that's necessarily bad for testing jars, but I'm not sure if that was intentional).

- [Same setup as last time](https://gyazo.com/4b99d891e4d22ca2f675c4d5773ada75)
- [No errors in game when reloading](https://gyazo.com/6da9ab9d4bdb7f605df8e40e6969416c)
- [Tons of debug in console, and a few errors in between that don't make sense](http://www.hastebin.com/opanuyokeg.md) (e.g. `there's no loop that matches 'loop player's uuid'` error right in the middle of a `loop all players` loop

[Here's the script in question](http://www.hastebin.com/ipimiqohod.vbs) so you can see what lines are throwing the errors. I really think at this point though, it would be best to make this into two branches; one that moves forward [from dev20b, before the new parser](https://github.com/bensku/Skript/releases/tag/dev20b) with 1.11 support (with your new mob registrations and such from dev22), and one that continues from where you are now with the new parser. Cause at this rate, 1.11 support with addons will be a long ways off. Nobody using Skript can really play on 1.11 as it stands. The branches could be merged once the new parser works (and I'm happy to continue testing it), and it shouldn't take that long to get dev20b running on 1.11, especially since you've already coded the most important 1.11 support stuff.

**Comment by bensku** [comment] 2016-11-27 21:39
The thing is, dev20b parser is not capable of supporting all my additions. Even worse, many commits contain 1.11 stuff (and general enhancements) and parser updates.

I'll try anyway. If I fail, it might be best idea for someone to fork Skript again...

**Comment by TheBentoBox** [comment] 2016-11-27 21:52
I understand. I have faith in you; and I think it would take a lot of the stress off of you if there was a dev20b-based 1.11 version out that people could use while you work on the parser. Then getting this working wouldn't be such a time sensitive thing anymore.

**Comment by PugaBear** [comment] 2016-11-27 23:59
^ Id appreciate that (and [suggested it here](https://github.com/bensku/Skript/issues/239#issuecomment-261626491)

**Comment by Legoman99573** [comment] 2016-12-02 04:03
It seems that the latest release has actually made most scripts work like they did back in 1.10, plus the old parser is back, so now it's easier to know how many errors were made in the code. Please keep it on the old parser as it actually knows what it is doing ;)

**Comment by bensku** [comment] 2016-12-02 12:40
I will keep old parser as long as it works. But... Well, my hack to compile it kinda unstable. Preprocessing Java code by Bash script is just as bad idea as it sounds :)

**Closed** 2017-08-25 13:10 UTC
Labels: bug, new-parser

**Comment by Encode17** [comment] 2018-04-22 13:01
This bug is happening again in newest version :(
[make player execute command "hub"] is not a valid lambda statement.

**Comment by Encode17** [comment] 2018-04-22 20:55
Is there any way to fix it? It was working on my 1.10 server before upgrade.

**Comment by bensku** [comment] 2018-04-23 07:59
Well, I have no idea what your problem is. Maybe?

**Comment by Legoman99573** [comment] 2018-04-23 08:59
@Encode17 using spigot, paperspigot, or craftbukkit?

**Comment by Encode17** [comment] 2018-04-23 11:46
Spigot. Java 1.8. OS: Debian.

**Comment by TheLimeGlass** [comment] 2018-04-24 10:59
Hi i'm Lime, das me the tag hi.

SkQuery throws an error when the effect/condtions within the lambda are invalid. The original issues of this was due to the multi-threaded parser.

@Encode17 Provide your coding please.

This is a SkQuery issue and also could potentially be user error, so this issue may be closed.

**Comment by Encode17** [comment] 2018-04-24 12:18
I have everything default in config. Where can I check the "coding"?
