### ISSUE TITLE
SkQuery Hotbar

### ISSUE THREAD

**Issue by Weefle** [bensku/Skript#503] opened 2017-04-14 13:48 UTC
I get an error what I've never got before with this script: https://hastebin.com/raw/dizonixije
Skript version: 2.2-dev26d
Spigot: 1.11.2
This script works fine with skript 2.2-dev25
The error: https://hastebin.com/raw/osagixocub

**Comment by TheBentoBox** [comment] 2017-04-14 14:41
Well, it's SkQuery code, but it does look like a vanilla Skript error, probably related to #497. Will see what bensku thinks.

**Comment by bensku** [comment] 2017-04-14 17:49
Skript bug, *and* duplicate of #497.

**Closed by bensku** 2017-04-14 17:49 UTC
Labels: dev-needed
