### ISSUE TITLE
'size of %objects%' expression conflict

### ISSUE THREAD

**Issue by Pugabyte** [bensku/Skript#876] opened 2017-09-19 14:36 UTC
Updated to dev31c earlier today, now my homes stuff doesn't work.

http://paste.bear-nation.net/skript

![](https://i.imgur.com/BPrBlCH.png)

I worked around the error by just looping the list variable and adding 1 to a counter, so a fix is not urgent for me.

**Comment by TheBentoBox** [comment] 2017-09-19 14:51
This looks more like an addon issue to me because one of your addons is interpreting the `size of` expression as you attempting to get the border length of a world. Even if updating Skript caused this, it's like just due to some parsing changes that wouldn't be an issue if that addon wasn't overriding vanilla Skript syntax with its own. Will wait for more confirmation from others though.

**Comment by Snow-Pyon** [comment] 2017-09-19 14:54
Well, it's an issue in its way, Skript wasn't behaving like this before so this is a new parser bug. Also, yeah, MundoSK has a `size of %world%` expression which may cause the issue, but again, this is a Skript bug.

**Comment by TheBentoBox** [comment] 2017-09-19 15:42
IMO addons should not use the same syntax as an old and insanely commonly used vanilla Skript syntax. In theory, the parser should be able to handle it, but the variables are abstracted behind a list which could contain a myriad of different data types since Skript is weakly typed, so there's really no "correct" way for Skript to treat an entire list. It's going to cause issues like this when other addons register syntax that conflicts with the vanilla syntax. 

That being said, I guess it's technically a bug as you said, since this didn't happen previously. Hopefully it's an easy fix!

**Comment by bensku** [comment] 2017-09-19 20:33
Sometimes old bugs fixed break new stuff, and I cannot sadly test with all addons. But we'll see oncr I can take a look at this.

**Comment by TlatoaniHJ** [comment] 2017-09-22 13:35
MundoSK 1.7.5-BETA.10.22 has a fix for this conflict: a config option has been added which disables the use of `size` in border syntaxes in favor of 'diameter', removing the conflict with the original `size of %objects%` syntax in Skript.

However, the conflict seems to have been caused by a weird behavior in the latest versions of Skript (I think dev30 and later) where syntaxes that should only allow single expressions are now allowing non-single expressions. For example, with the following code:
`command /test:
    trigger:
        broadcast "%{_temp::*} times%"`
In dev29, this code gives an error when the script is loading (<...> times can only accept a single number, not more)
However in dev31c, this command will load, but give the following exception when it's run: https://hastebin.com/wutarogugu.md

**Comment by bensku** [comment] 2017-09-22 13:45
Hmm, interesting... I may have broken something when tinkering with parser. Actually, that is very likely.

I'll take a look, hopefully before next release.

**Comment by bensku** [comment] 2017-10-27 14:50
@TlatoaniHJ Your test case gives the error correctly. Maybe I 'accidentally' fixed it while changing other stuff. Please try again with new release (not yet published). If it works without addons, please try again to see if it stops working.

**Comment by Syst3ms** [comment] 2018-02-27 09:42
Shouldn't this be given a more appropriate name? It's more related to the parser than anything else.

**Comment by Nicofisi** [comment] 2018-02-27 09:57
To be fair 95% of the issues here could have way better names lol @Syst3ms

**Closed** 2018-02-28 00:45 UTC
Labels: bug
