### ISSUE TITLE
Can't use "difference between" with timespans with variables

### ISSUE THREAD

**Issue by Louis-D** [bensku/Skript#459] opened 2017-04-02 19:22 UTC
This is a very weird behavior

set {_diff} to difference between {_diff} and 50 minutes <-- works

set {_timespan} to 50 minutes
set {_diff2} to difference between {_diff} and {_timespan} <-- doesn't work

**Comment by Snow-Pyon** [comment] 2017-04-02 19:24
Duplicate of #450.

**Closed** 2017-04-02 20:06 UTC
