### ISSUE TITLE
Size of list / on place/ id of block

### ISSUE THREAD

**Issue by epicskymi** [bensku/Skript#921] opened 2017-10-11 07:44 UTC
https://pastebin.com/r1AwsUFb

dev 31c
1.12.1

line's in question 

    set {_s} to size of {Natures::*}

worked in v29
back to v29 I go

Also on place: in v29 doesn't set player but it does in v31 

also in v29
on rightclick:
    broadcast "%id of event-block%"

will crash your server if you rightclick a bunch no logs no error server locks up and freezes untill u close the console

I know its this however bc it occurred after adding and it stopped occurring after removing it and still hasen't crashed 3 days later

**Comment by TheBentoBox** [comment] 2017-10-11 13:04
The first part duplicates #876 .

I'm not sure what you mean by "in v29 doesn't set player"

Broadcasting messages seems to be a bit slow, but I don't know if it's necessarily an issue that spam-broadcasting a ton of debug messages can cause issues because I don't see a legitimate situation where you'd want to do something like what you sent here.

Probably going to close unless you can clarify more about the `on place` issue, but this issue is already a bit of a mess and the initial reasoning you had for posting (the `size of %objects%` issue) is a duplicate.

**Comment by epicskymi** [comment] 2017-10-11 15:56
On place:
    Broadcast "%player%" 
Will alwayd display none 
In v29 but in v31 it displays the player

**Comment by epicskymi** [comment] 2017-10-11 15:57
As for the broadcast I do alot of it without issues 156+ at once and it never crashed I put those 2 lines and server cant stay up longer the. 2 mins

**Comment by Snow-Pyon** [comment] 2018-04-23 08:48
Duplicate of #876.

**Closed by Snow-Pyon** 2018-04-23 08:48 UTC
