### ISSUE TITLE
Server Shuts Down When I Reload My Skript

### ISSUE THREAD

**Issue by YunusGG** [bensku/Skript#623] opened 2017-06-02 22:56 UTC
Like header.
When I reload my big skripts (about 200 lines) my server shut down and it restarts.
There is no errors and warns.
What should I do ?

**Comment by TheBentoBox** [comment] 2017-06-02 23:41
Errors? Script in question? Server version? Skript version? You need to provide at least some details dude, you can't just come here with a really vague question and expect us to know what to do.

Also, unless you can point out a bug in the parser or something that would cause this to happen, then this isn't the place to report an issue like this. I'll give you a little time to try to do so, but for generic help that's not related to Skript bugs or feature requests you need to ask on the skUnity forums, not here.

**Comment by Sam1370** [comment] 2017-06-18 16:03
This is probably a duplicate of #636. The server shuts down when you reload the skript because it takes so long and Spigot freaks out.

**Comment by TheBentoBox** [comment] 2017-06-18 16:58
I guess it's more accurate that 636 duplicates this since this game first, but given there's more info on 636 and the reporter never responded...

**Closed by TheBentoBox** 2017-06-18 16:58 UTC
