### ISSUE TITLE
[Feature Request] Instance Variables

### ISSUE THREAD

**Issue by JRoy** [bensku/Skript#1179] opened 2018-04-09 00:45 UTC
After seeing a post on skUnity about this, I think it could be useful: Instance Variables. An instance variable would store variables in ram and not be persistent over reboots, on purpose. These would work much like how temporary variables works so a prefix to mark something as an instance variable (I was thinking "-" or "@").  Also looking at the code for Variables, it looks like this would relatively easy to implement as I see some basic support for this.

**Comment by Snow-Pyon** [comment] 2018-04-09 00:52
Duplicate of #1049.

**Closed by Snow-Pyon** 2018-04-09 00:52 UTC
