### ISSUE TITLE
PlayerInteractEvent on right click

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#266] opened 2016-11-30 20:06 UTC
Spigot 1.11 (latest build) and Skript 2.2-dev22c. Skript seems to be handling all right-click events on signs, even those not intended for it. I have no right-click events in any Skript/script. I have configured a lot of CommandSigns signs, which until this configuration handled those events. For each right-click, console/log reports:

`[12:01:45 INFO]: [Skript] PlayerInteractEvent`

**Comment by RoyCurtis** [comment] 2016-11-30 20:18
Duplicate of #265

**Comment by SlimeDog** [comment] 2016-11-30 20:23
#265 just reports the spam. I'm reporting mishandling of right-click events.

**Comment by SlimeDog** [comment] 2016-11-30 21:18
But I was mistaken. :(

Just spam. So duplicate of #265.

**Closed** 2016-11-30 21:18 UTC
