### ISSUE TITLE
Functions only work when they're in the same file as function-call (aka "Functions... i dont even")

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#829] opened 2017-08-30 19:13 UTC
```
[15:09:55 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLo
[15:09:55 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(Scrip
[15:09:55 ERROR]: #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.ja
[15:09:55 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(Skript
[15:09:55 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(Plug
[15:09:55 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(
[15:09:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.d
[15:09:55 ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java
[15:09:55 ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.
[15:09:55 ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(Eff
[15:09:55 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52
[15:09:55 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerI
[15:09:55 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerI
[15:09:55 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.j
[15:09:55 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2
[15:09:55 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(
[15:09:55 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand
[15:09:55 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCom
[15:09:55 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.Method
[15:09:55 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(T
[15:09:55 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEven
[15:09:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEve
[15:09:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEve
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectio
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectio
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInCha
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInCha
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectio
[15:09:55 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapte
[15:09:55 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTas
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(S
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer
[15:09:55 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer
[15:09:55 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:09:55 ERROR]: #!#!
[15:09:55 ERROR]: #!#! Version Information:
[15:09:55 ERROR]: #!#!   Skript: 2.2-dev30d
[15:09:55 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[15:09:55 ERROR]: #!#!   Minecraft: 1.12.1
[15:09:55 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM
[15:09:55 ERROR]: #!#!   OS: Linux amd64 4.10.0-20-generic
[15:09:55 ERROR]: #!#!
[15:09:55 ERROR]: #!#! Running CraftBukkit: false
[15:09:55 ERROR]: #!#! Running Spigot (or compatible): true
[15:09:55 ERROR]: #!#! Running Paper (or compatible): true
[15:09:55 ERROR]: #!#!
[15:09:55 ERROR]: #!#! Current node: jaygolfGUIMainMenu(command sender) (ja
[15:09:55 ERROR]: #!#! Current item: null
[15:09:55 ERROR]: #!#! Thread: Server thread
[15:09:55 ERROR]: #!#!
[15:09:55 ERROR]: #!#! Language: english
[15:09:55 ERROR]: #!#! Link parse mode: DISABLED
[15:09:55 ERROR]: #!#!
[15:09:55 ERROR]: #!#! End of Error.
[15:09:55 ERROR]: #!#!
```

related function:

```
# main menu
function jaygolfGUIMainMenu(player: player):

    create a gui with virtual chest with 2 rows named "Main Menu":
        set {_filler 1} and {_filler 2} to stained glass pane named "&r"
        set data value of {_filler 1} to 8
        set data value of {_filler 2} to 7
        loop 9 times:
            make next gui slot with {_filler 1}
        loop 9 times:
            make next gui slot with {_filler 2}
        
        set {_solo} to unbreakable diamond hoe
        set data value of {_solo} to 101
        set 1st line of {_solo}'s lore to "&7Play a solo game"
        format gui slot 0 with {_solo} named "&f&lSolo":
            execute player command "/golf p solo"
        
        format gui slot 17 with barrier named "&c&lClose":
            close player's inventory
            
    open last gui to {_player}
```

tuske 1.8.1
skript dev30d

this happens to literally all my functions, they became completely useless and i dont know where the issue lies

**Comment by TheBentoBox** [comment] 2017-08-30 20:51
I fixed your formatting; check how the post is formatted now so you can know how to properly format code in the future. Additionally, your stack trace is largely cut off so it's hard to read what's going on. You should update your post with the error in full. Lastly, I'm not even sure if this is a vanilla Skript issue since it seems to be related to TuSKe's GUI effects, so this may not even be the correct place to report it. If this only started happening with version dev30d then it probably is a Skript issue.

**Comment by Snow-Pyon** [comment] 2017-08-30 23:06
If I'm not wrong, he might be talking about the following stack trace:
https://gist.github.com/Snow-Pyon/a01955f2d1209f7f1fc79aa10566d59b

Which is a pretty annoying bug that happens sometimes when reloading scripts in the dev30d, after throwing the first stack trace it'll not let you reload the script anymore even if you remove every function from it, and the only way to fix it is restarting the server. And yes, I've tried without addons.

**Comment by jaylawl** [comment] 2017-08-30 23:13
>  it'll not let you reload the script anymore even if you remove every function from it, and the only way to fix it is restarting the server. And yes, I've tried without addons.

This is something i can confirm. As i originally stated i am super thrown off by hoards of bugs, i got into Skript for the first time since 1.10 and lots of things have changed (speaking of updates), so im having a hard time providing proper information - will provide asap tho, as soon as i discover related errors

**Comment by bensku** [comment] 2017-08-31 06:49
@Snow-Pyon That bug is fixed and is waiting for new release. I have some more things in my TODO list before can release, though...

I'm not joking when I mark everything "pre-release". Stability and user experience may vary greatly.

**Comment by Snow-Pyon** [comment] 2017-08-31 11:16
Eh, don't get me wrong, I know that you don't just put as `pre-release` something for no reason. I just reported the bug with the information I can provide of it. And I knew the bug was fixed but I wasn't sure at all.

I know the risks of running a pre-release but I still use them as someone has to report these kind of bugs haha.

**Comment by bensku** [comment] 2017-08-31 14:10
The latter was more to OP than you, just used same message to inform you that I fixed a bug :) Sorry if I caused misunderstanding.

**Comment by jaylawl** [comment] 2017-08-31 15:20
Is there something specific i could test in order to provide more useful information? Any guidelines? I'd love to be more theural.

**Comment by Snow-Pyon** [comment] 2017-08-31 16:02
What you always should provide is:

* Full stack trace (which provides a the java, spigot/PaperSpigot, skript version and a list of addons used).
* How you have reproduced this bug step by step.
* The code to reproduce this bug, and if it's a problem with some expression/effect or other provide the exact line where it errors.
* Explain what the bug causes and if it's something critical or not totally (considering Skript in general and not your server, there could be other several bugs that should be fixed before yours).

The bug that you had will be fixed for the next release anyways, it's just matter of wait for it. The above list is just a "so you know" for any other issue you want report.

**Comment by jaylawl** [comment] 2017-09-01 20:21
@bensku , tagging you because im not sure you'll check this topic again otherwise, sorry if im doing you wrong :|

I've come over something with this issue. I'm currently building a game in which the use of function would cut the amount of code in half, so i got eager to try it again.

First off, here's the code (complete file here: https://hastebin.com/ozimubupen.vbs):
```
    addStats("%{_player}'s uuid%", "Statistics.Strokes", {_currentstrokes})
    addStats("%{_player}'s uuid%", "Statistics.Holes", 1)
    addStats("%{_player}'s uuid%", "%{_score::stat}%", 1)
```
related function (this is the complete file content, too (this makes use of the add-on "SkUtilities")):
```
function addStats(player: text, stat: text, value: number):
    set {_file} to "plugins/Skript/scripts/jaygolf/playerdata/%{_player}%.yml"
    if file "%{_file}%" does not exist:
        create file "%{_file}%"
    if yml path "%{_stat}%" in file "%{_file}%" does not exist:
        set yml value "%{_stat}%" of file "%{_file}%" to {_value}
    else:
        set {_total} to yml value "%{_stat}%" of file "%{_file}%"
        set yml value "%{_stat}%" of file "%{_file}%" to ({_total} + {_value})
```

This function actually worked properly after first reloading it! When it worked, i only had the first two lines of the former codepaste added. Then i added the third line and reloaded (code of the function was not changed), that's when it seized to work - actually a bunch of related scripts seem to no longer work. I did not reload using /skript reload all, but i made my own script that reloads all scripts containing the specific string i provide. (In this case, i would use "/srs golf")

https://snag.gy/ceH3gi.jpg

Right now, im further investigating this.

**Comment by jaylawl** [comment] 2017-09-04 00:49
**This issue appears to be resolved by dev31!**

**Closed** 2017-09-04 05:02 UTC
