### ISSUE TITLE
Classinfo registration error on script load

### ISSUE THREAD

**Issue by MotoSolar** [bensku/Skript#317] opened 2016-12-28 07:16 UTC
[16:09:20] [Server thread/ERROR]: #!#! Stack trace:
[16:09:20] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:337)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:415)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:1)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:85)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:68)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:407)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:686)
[16:09:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:141)
[16:09:20] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:09:20] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:09:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[16:09:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[16:09:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:437)
[16:09:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:09:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[16:09:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[16:09:20] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:09:20] [Server thread/ERROR]: #!#! 
[16:09:20] [Server thread/ERROR]: #!#! Version Information:
[16:09:20] [Server thread/ERROR]: #!#!   Skript: 2.2-dev22g
[16:09:20] [Server thread/ERROR]: #!#!   Bukkit: 1.10-R0.1-SNAPSHOT
[16:09:20] [Server thread/ERROR]: #!#!   Minecraft: 1.10
[16:09:20] [Server thread/ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[16:09:20] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[16:09:20] [Server thread/ERROR]: #!#! 
[16:09:20] [Server thread/ERROR]: #!#! Running CraftBukkit: false

**Comment by TheBentoBox** [comment] 2016-12-28 15:42
What were you doing that caused this error? Did you reload a script, reload your server, restart your server?

**Comment by MotoSolar** [comment] 2017-01-01 03:56
When I Start the server 
None of my scripts were enable
and when I enable all of them
I got that error

**Comment by TheBentoBox** [comment] 2017-01-02 20:33
Do you get this error every time you start up the server?

**Comment by MotoSolar** [comment] 2017-01-03 08:32
Every Single Times.

**Comment by TheBentoBox** [comment] 2017-01-17 16:05
Can you check if you're still having this issue on dev23?

**Comment by MotoSolar** [comment] 2017-01-18 06:24
I also try it before 
But still same
none of scripts were work

**Comment by MotoSolar** [comment] 2017-01-18 06:30
![image](https://cloud.githubusercontent.com/assets/23397550/22053285/0459e00e-dd93-11e6-8004-2500c92b5f47.png)

**Comment by bensku** [comment] 2017-06-01 17:34
Checking back here again, haven't ever seen this again. Still an issue?

**Comment by Mart100** [comment] 2017-07-31 15:59
I've got the exact same error today. with dev29. 
![afbeelding](https://user-images.githubusercontent.com/27071508/28786498-b116556a-7619-11e7-9dee-08c1436e7cc5.png)

When I reload its loading the skripts but also says there are no skripts.
But when i try to enable them it says they are already enabled i just have to start them. The files are just in the scripts map. without an -. And it gives the same console error as above.

**Comment by bensku** [comment] 2017-07-31 16:04
@Mart100 Not likely related to this issue even if looks similar. Open a new one.

**Comment by Snow-Pyon** [comment] 2018-04-20 21:13
Since the author didn't give a response and the causes of this error are still unknown, I'm closing this. Please open another issue if you get this error again with more info of what could cause it.

**Closed by Snow-Pyon** 2018-04-20 21:13 UTC
Labels: bug, needs more info
