### ISSUE TITLE
Only placed blocks are getting looped

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#277] opened 2016-12-05 20:31 UTC
I wanted to loop a sapling in a worldedit schematic but it didnt work.
Then, I realised that only placed saplings by players are getting looped.
Any solution?

**Comment by bensku** [comment] 2016-12-06 16:56
What exactly are you trying to do? Please provide code sample.

**Comment by YellowZaki** [comment] 2016-12-06 16:59
A skript to grow saplings when you are close to it, and you sneak several times. Here is the skript:

on sneak toggle:
	player is sneaking
	if player has 1 bone meal:
		loop blocks in radius 3:
			if loop-block is 6:0:
				set {_alea} to a random integer between 1 and 4
				if {_alea} is 2:
					remove 1 bone meal from player's inventory
					set loop-block to air
					grow small oak tree at the loop-block
					execute console command "/particle happyVillager %loop-block's x coordinate% %loop-block's y coordinate% %loop-block's z coordinate% 1 1 1 1 100 normal %player%"			
				else:
					remove 1 bone meal from player's inventory
					execute console command "/particle angryVillager %player's x coordinate% %player's y coordinate% %player's z coordinate% 1 1 1 1 40 normal %player%"
		
	else:
		loop blocks in radius 3 around the player:
			if loop-block is 6:0:
				set {_alea} to a random integer between 1 and 20
				if {_alea} is 10:
					set loop-block to air
					grow small oak tree at the loop-block
					execute console command "/particle happyVillager %loop-block's x coordinate% %loop-block's y coordinate% %loop-block's z coordinate% 1 1 1 1 100 normal %player%"
				else:
				execute console command "/particle angryVillager %player's x coordinate% %player's y coordinate% %player's z coordinate% 1 1 1 1 40 normal %player%"

**Comment by bensku** [comment] 2016-12-10 10:41
Soo... If you place sapling by hand (and using /setblock, maybe?), this works. If you use WorldEdit, this doesn't.

I can't think how this could be caused by Skript, but will test as soon as possible. Meanwhile, make sure your Spigot and WorldEdit are up to date... This sounds almost like Spigot bug or world corruption.

**Comment by TheBentoBox** [comment] 2016-12-28 02:06
This is probably because saplings use different data values to indicate whether or not they are about to grow, and you're detecting very specifically saplings with data value of 0.

Can you run a data value test on some of the saplings that refuse to grow and see that their data value is? Use `send "%data value of target block%"` in an effect command or in a test command, and see what data value the argumentative saplings have. It'll probably be 6 or something instead of 0.

Please give feedback with your results. If we don't hear back from you within a number of days, I will close this issue.

**Comment by YellowZaki** [comment] 2016-12-28 16:25
It is showing the data value 6:8 It is strange. Others saplings placed with worldedit conserve their original datavalue. All, except the oak sapling.
So now the issue is resolved, thank you :D

**Comment by YellowZaki** [comment] 2016-12-28 16:49
This is another issue related to grow:
Only oak tree type works. If I use grow small jungle tree/grow birch tree..., it says; Can't understand event/condition
Just works: grow small oak tree

**Comment by TheBentoBox** [comment] 2016-12-28 17:06
Some of those can be fixed by adding an extra "tree". Weird, I know, but `grow small jungle tree tree at target block` works. It's probably because the first `tree` is part of the tree type name.

That is another issue though, so if you find that you aren't able to get certain trees to grow (including by adding the extra "tree"), please open another issue.

**Closed by TheBentoBox** 2016-12-28 17:06 UTC
