### ISSUE TITLE
Adding loop-item to a variable/list is broken!

### ISSUE THREAD

**Issue by WolfezzKyne** [bensku/Skript#22] opened 2016-03-18 12:12 UTC
Code to test it:

```
on death of player:
	if victim's inventory contains a dirt:
		chance of 50%:
			remove a dirt from drops
			loop items in victim's inventory:
				remove loop-item from drops
				add loop-item to {inventory.%name of victim%::*}
			
on respawn:
	add {inventory.%name of player%::*} to player's inventory
	delete {inventory.%name of player%::*}
	stop
```

**Comment by Pilvinen** [comment] 2016-03-20 08:37
Does it work if you add the item to list and THEN remove it from inventory?

**Comment by Pilvinen** [comment] 2016-03-20 08:49
Try what this gives you:
1) Grab some items.
2) Load skript below.
3) Die.

```
on death of player:
  loop items in victim's inventory:
    add loop-item to {inventory.%name of victim%::*}

  loop {inventory.%name of victim%::*}:
    broadcast " DEBUG: loop-index: %loop-index%, loop-value: %loop-value%"
```

**Comment by WolfezzKyne** [comment] 2016-03-20 15:24
it gives the right output... strange.. but for some reasons, it doesn't gives the items
Tested this:
`on death of player:
  loop items in victim's inventory:
    add loop-item to {inventory.%name of victim%::*}
on respawn:
  loop {inventory.%name of player%::*}:
    broadcast " DEBUG: loop-index: %loop-index%, loop-value: %loop-value%"`

No output ^^

**Comment by Pilvinen** [comment] 2016-03-20 15:38
It could be the old bug that's been around for ages where in some cases %name of victim/player% or possibly %victim/player% from some events doesn't pass over correctly to other events. It gets corrupted somehow.

I'm not 100% sure how to reproduce it but it definitely needs some serious fixing.

The usual way around this problem is to - for example:

```
on death of player:
    set {_playerUUID} to UUID of victim
    if victim's inventory contains a dirt:
        chance of 50%:
            remove a dirt from drops
    loop items in victim's inventory:
        add loop-item to {inventory.%{_playerUUID}%::*}
        remove loop-item from drops

on respawn:
    set {_playerUUID} to UUID of player
    add {inventory.%{_playerUUID}%::*} to player's inventory
    delete {inventory.%{_playerUUID}%::*}
    stop

```

That should work, I think. If it doesn't try setting it as text -> set {_playerUUID} to "%UUID of victim%", that should basically always work no matter what.

**Comment by WolfezzKyne** [comment] 2016-03-20 15:51
Nope, does not work^^

**Comment by Pilvinen** [comment] 2016-03-21 00:42
One thing you could try would be adding 1 tick delay right after "on respawn:" because we've established that:

1) The list gets made -->
2) Therefore you should be able to access it.

Basically the player is still dead right when the respawn event happens so adding the items back to inventory not working might be attributed to that. After 1 tick delay the event has happened already and the player should be alive, so you might wish to try this:

```
on respawn:
    wait for 1 ticks
    set {_playerUUID} to UUID of player
    add {inventory.%{_playerUUID}%::*} to player's inventory
    delete {inventory.%{_playerUUID}%::*}
    stop
```

**Comment by WolfezzKyne** [comment] 2016-03-21 05:45
Still does not work

**Comment by Pilvinen** [comment] 2016-03-21 08:56
How about changing this part like this in the "on respawn" event:
```
loop {inventory.%{_playerUUID}%::*}:
    add loop-value to player's inventory
```

You could also try checking if you get any values:

```
loop {inventory.%{_playerUUID}%::*}:
    broadcast " DEBUG: %loop-index%: %loop-value%"
```

**Comment by WolfezzKyne** [comment] 2016-03-21 12:05
Broadcasting works, adding loop-value doesn't, but it loads without any error^^

**Comment by Pilvinen** [comment] 2016-03-21 13:27
Could be a bug then. Or several.

You could try:
```
    give loop-value to player
```

**Comment by WolfezzKyne** [comment] 2016-03-21 13:50
omg it's working xDD thanks :)

**Comment by bensku** [comment] 2016-03-25 13:28
Adding list of items to inventory is fixed in next release.

**Closed by bensku** 2016-03-25 13:28 UTC
Labels: bug
