### ISSUE TITLE
sorted, keep loop-index

### ISSUE THREAD

**Issue by aaa8881** [bensku/Skript#544] opened 2017-05-03 11:10 UTC
Hello,  I heard this is fixed ( or tried to be fixed ) in dev24, but it still doesn't seem to be working.
```
command /rankTest:
	trigger:
		delete {testList::*}
		delete {testListSorted::*}
		set {testList::A} to 2
		set {testList::B} to 5
		set {testList::C} to 8
		set {testList::D} to 1
		loop {testList::*}:
			message "%loop-index%, %loop-value%"
		set {testListSorted::*} to sorted {testList::*}
		loop {testListSorted::*}:
			message "%loop-index%, %loop-value%"
```

the output of this code is http://imgur.com/a/Hlpu0
Desired output is 
a,2
b,5
c,8
d,1
d,1
a,2
b,5
c,8

with indexs are kept. 
This is tested with dev25

**Comment by bensku** [comment] 2017-05-03 13:28
Duplicate of #202; this is definitely not supported yet.

**Closed by bensku** 2017-05-03 13:28 UTC
Labels: duplicate
