### ISSUE TITLE
1.12 can't use /sk reload DEV28-C

### ISSUE THREAD

**Issue by NebuSensei** [bensku/Skript#650] opened 2017-06-10 18:10 UTC
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:03:48] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[21:03:48] [Server thread/ERROR]: #!#! Used command: /sk reload kod
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:03:48] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:03:48] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[21:03:48] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:03:48] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:03:48] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:03:48] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! Stack trace:
[21:03:48] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[21:03:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:269)
[21:03:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:240)
[21:03:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:618)
[21:03:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:611)
[21:03:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[21:03:48] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:03:48] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:03:48] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:03:48] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:03:48] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:03:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:03:48] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! Version Information:
[21:03:48] [Server thread/ERROR]: #!#!   Skript: 2.2-dev28c
[21:03:48] [Server thread/ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[21:03:48] [Server thread/ERROR]: #!#!   Minecraft: 1.12
[21:03:48] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[21:03:48] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! Current node: null
[21:03:48] [Server thread/ERROR]: #!#! Current item: null
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! Thread: Server thread
[21:03:48] [Server thread/ERROR]: #!#! 
[21:03:48] [Server thread/ERROR]: #!#! End of Error.
[21:03:48] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment] 2017-06-10 18:21
Essentially duplicates #636, closing.

**Comment by TheBentoBox** [comment] 2017-06-10 18:22
Oh wait, I think I was on the wrong issue. Can you give and steps to reproduce this?

**Comment by NebuSensei** [comment] 2017-06-10 19:09
I download last version all addons and now i can't use sk reload command but skripts work fine

**Comment by bensku** [comment] 2017-06-10 20:45
Hmm, try without any addons please. It might be Skript bug... Or addons bug introduced in said new versions.

Also, are there any other errors in console?

**Comment by NebuSensei** [comment] 2017-06-10 21:03
it seems issue permissionex if i delete permissionex it's working

**Comment by TheBentoBox** [comment] 2017-06-10 21:15
That's really odd. How long has it been since you updated Pex?

**Comment by NebuSensei** [comment] 2017-06-10 23:17
I have pex last version v1.23.4

**Comment by NebuSensei** [comment] 2017-06-13 13:42
any solution?

**Comment by TheBentoBox** [comment] 2017-06-13 22:40
I can't reproduce this and don't have any issues with Pex or permissions on 1.12. I'd recommend updating your Spigot (make sure you're on the very latest version) and your Skript (dev29 is out now). But unless you or anyone else can tell us specifically what causes this there's really nothing we can do for you.

**Closed by TheBentoBox** 2017-06-13 22:40 UTC
