### ISSUE TITLE
Local variable shared between same events

### ISSUE THREAD

**Issue by 4rnoP** [bensku/Skript#1257] opened 2018-05-15 09:11 UTC
with this code:
```
on click:
	set {_test} to "TEST"

on click:
	send "%{_test}%"
```
I receive the message "TEST" in the chat, while the variable has not been defined in the second event.

**Comment by Snow-Pyon** [comment] 2018-05-15 09:16
Duplicate of #1095.

**Closed by Snow-Pyon** 2018-05-15 09:16 UTC

**Comment by supertassu** [comment] 2018-05-15 09:17
Duplicate of #1095
