### ISSUE TITLE
Main/off hand issue

### ISSUE THREAD

**Issue by DevilishDante** [bensku/Skript#1079] opened 2018-01-27 20:33 UTC
Hello i have many problem with "on right click" in deed,
when a player has both a item in main and off hand on right click doesn't detect anymore
same with a spécial renamed item in main or off hand :/

skript version: lastest (this bug are présent in previously release)

**Comment by TheBentoBox** [comment] 2018-01-27 21:09
I cannot reproduce this, can anyone else?

**Comment by bensku** [comment] 2018-01-29 11:16
What Minecraft version are you using @DevilishDante?

**Comment by bi0qaw** [comment] 2018-01-29 12:20
Could not reproduce it either. Make sure that you have items in your hand that actually call the event!

**Comment by DevilishDante** [comment] 2018-01-29 13:02
@bensku i'm using 
CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

@bi0qaw and @TheBentoBox 
for example i'm using this code
`
command /bonemeal:
	permission: bone.admin
	permission message: &cVous ne pouvez pas faire cette commande!
	trigger:
		give bone meal named "&8&k10&r &6Super Poudre d'os &8&k10&r" with lore "&8> &aBoum! magique!||&8> &aDans un rayon de &250 Blocks" to player
		message "{@Prefix}&7Super poudre d'os en action !" to player

on right click with bone meal:
	if player is holding a bone meal named "&8&k10&r &6Super Poudre d'os &8&k10&r" with lore "&8> &aBoum! magique!||&8> &aDans un rayon de &250 Blocks" in off hand:
		if player is holding a bone meal in main hand:
			cancel event
			message "&8[&2&l!&r&8] &r&cVous ne pouvez utiliser qu'une seule poudre d'os à la fois!" to player
		else:
			if targeted block is a grass block:		
				loop blocks in radius 50 of block:
					if loop-block is grass block:
						if block above loop-block is air:
							chance of 70%:
								set block above loop-block-1 to 31:1		
							chance of 5%:
								set block above loop-block-1 to red tulip:4
							chance of 2%:
								set block above loop-block-1 to orchid:1
							chance of 2%:
								set block above loop-block-1 to red poppy:0
							chance of 2%:
								set block above loop-block-1 to fern:2					
							chance of 5%:
								set block above loop-block-1 to dandelion:0
	else if player is holding a bone meal named "&8&k10&r &6Super Poudre d'os &8&k10&r" with lore "&8> &aBoum! magique!||&8> &aDans un rayon de &250 Blocks" in main hand:
		if player is holding a bone meal in off hand:
			cancel event
			message "&8[&2&l!&r&8] &r&cVous ne pouvez utiliser qu'une seule poudre d'os à la fois!" to player
		else:
			if targeted block is a grass block:		
				loop blocks in radius 50 of block:
					if loop-block is grass block:
						if block above loop-block is air:
							chance of 70%:
								set block above loop-block-1 to 31:1		
							chance of 5%:
								set block above loop-block-1 to red tulip:4
							chance of 2%:
								set block above loop-block-1 to orchid:1
							chance of 2%:
								set block above loop-block-1 to red poppy:0
							chance of 2%:
								set block above loop-block-1 to fern:2					
							chance of 5%:
								set block above loop-block-1 to dandelion:0`

separately the special bone powder works but with an item like a shield or something else it does not matter if it's the main hand or the secondary one it does not work, I even try without the "in hand / off hand"

thanks to read me

**Comment by TheBentoBox** [comment] 2018-03-05 15:57
Since multiple people couldn't reproduce this and it hasn't really been reported by anyone else, I'm going to close this. I think if anything this is related to some other offhand/click event issues which we already have opened.

**Closed by TheBentoBox** 2018-03-05 15:57 UTC
