### ISSUE TITLE
Strings have issues with "the" when "the" is followed by an expression

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#1176] opened 2018-04-06 18:55 UTC
Take these codes:
```
broadcast "the the %{variable}%"
message "the the %{variable}%"

set {string} to "the the %{variable}%"
broadcast "%{string}%"
```
all of these will have the result `the <none>` instead of `the the <none>`

this can be fixed by putting a color code after the final `the`, e.x. `broadcast "the the&r %{variable}%"`

Tested without any addons on dev34
![image](https://user-images.githubusercontent.com/28607612/38439147-321ca30c-39a2-11e8-9ebf-826a1c4a0956.png)

**Comment by Snow-Pyon** [comment] 2018-04-06 19:41
Duplicate of #367

**Closed by Snow-Pyon** 2018-04-06 19:41 UTC
