### ISSUE TITLE
1.11.2 "Lightning" can not be used in Damage Cause

### ISSUE THREAD

**Issue by GreatRaceofGithub** [bensku/Skript#415] opened 2017-03-04 11:22 UTC
It seems to go if "void"
No error occurred when reloading ...

http://imgur.com/a/yVkTa

**Comment by TheBentoBox** [comment] 2017-03-04 20:09
Cannot reproduce:

## Setup:
**Spigot:** git-Spigot-d4f98a3-4448a7e (MC: 1.11.2)
**Skript:** 2.2-dev25 (today's release, March 4th 2017)

## Test Code:
I used the following (to test multiple syntaxes and stringifying the damage cause):
```
on damage:
	if damage cause is lightning:
		broadcast "SUCCESS: damage cause was lightning"
	else:
		broadcast "FAIL: damage cause was lightning"
		
	if "%damage cause%" is "lightning":
		broadcast "SUCCESS: ""%%damage cause%%"" is ""lightning"""
	else:
		broadcast "FAIL: ""%%damage cause%%"" is ""lightning"""
		
	if damage was caused by lightning:
		broadcast "SUCCESS: damage was caused by lightning"
	else:
		broadcast "FAIL: damage was caused by lightning"
	
	broadcast "%damage cause%"
```

## Result
I ran the following two commands:
```
# This is a vanilla Minecraft command to strike lightning
/summon minecraft:lightning_bolt
# Then a Skript effect command
|strike lightning at the player
```

My results are as follows:
![image](https://cloud.githubusercontent.com/assets/6902229/23581885/04a9cc14-00ec-11e7-8c0e-ebf1896a3ae8.png)

As you can see, it works fine for me. How are you spawning the lightning? If you are using a separate plugin, you can't guarantee that it's properly spawning in normal lightning which is dealing the correct damage type (it may be spawning in a fake lightning effect and manually damaging the player, which could register the damage type as `unknown` or `void`).

Unless you can show that this is an issue on Skript's end, I'll be closing this shortly.

**Closed** 2017-03-07 15:38 UTC
