### ISSUE TITLE
Expressions resets format codes on dev27

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#599] opened 2017-05-26 09:08 UTC
![image](https://cloud.githubusercontent.com/assets/19474570/26488330/5039f03e-4203-11e7-9481-2b4f3d333a70.png)

Same with JSON Chat: `<url:https://www.google.com>%player% test`

**Comment by Snow-Pyon** [comment] 2017-05-26 10:21
Duplicate of #528. To close.

**Closed** 2017-05-26 11:36 UTC
