### ISSUE TITLE
Another dev30b error

### ISSUE THREAD

**Issue by Sashie** [bensku/Skript#782] opened 2017-08-07 23:05 UTC
`[ERROR] [Skript] event-projectile is not a world (test.sk, line 2: broadcast "%type of event-projectile%"')`

Using..
```
on projectile hit:
	broadcast "%type of event-projectile%"
```

**Comment by Snow-Pyon** [comment] 2017-08-07 23:19
Duplicate of #779.

**Comment by Sashie** [comment] 2017-08-08 00:23
I didn't see this error specifically mentioned in there

**Comment by Snow-Pyon** [comment] 2017-08-08 02:24
This is an issue related to the type of expression being broken which was reported in that issue.

**Comment by bensku** [comment] 2017-08-08 13:28
Bug fixed.

**Closed** 2017-08-08 13:28 UTC
Labels: bug
