### ISSUE TITLE
Sign Text Vanishes

### ISSUE THREAD

**Issue by BartlettRock** [bensku/Skript#184] opened 2016-09-02 05:00 UTC
I don't believe it's a addon error, because I've disabled all of my addons, and it still fails.
My problem is setting text to any line on a sign.
If I make a sign, with text normally, it stays.
But if I use skript to change a line, it makes all the text on the sign disappear.

I would post any error logs, if there were any....

**Comment by TheBentoBox** [comment] 2016-09-02 15:59
It works fine for me, what version is your server & what version of Skript do you have?

**Comment by BartlettRock** [comment] 2016-09-03 18:02
The latest version of Bensku Skript. My server is 1.10

**Comment by bensku** [comment] 2016-09-06 16:04
Please list your plugins, this is very strange. And update your Spigot just in case you had old version causing problems.

**Comment by BartlettRock** [comment] 2016-09-08 04:17
List of plugins:
WildSkript - 1.9, Skript - 2.2-dev19, Skellett - 1.4.9, Umbaska - 2.0 Beta
5.5.1 for Minecraft 1.10, SkQuery - 3.22.1
List of addons:
Skellett v1.4.9, Umbaska v2.0 Beta 5.5.1 for Minecraft 1.10, SkQuery
v3.22.1, WildSkript v1.9

Skript Version: 2.2-dev19
Spigot Version: 1.10.2-R0.1-SNAPSHOT

**Comment by bensku** [comment] 2016-10-25 17:32
Can't reproduce. Closing.

Note that Umbaska 2 might be the thing which is causing problems...

**Closed by bensku** 2016-10-25 17:32 UTC
