### ISSUE TITLE
Error resolving offline players?

### ISSUE THREAD

**Issue by JonBowman** [bensku/Skript#549] opened 2017-05-07 17:37 UTC
The error that popped into my console when I loaded Skript. Idk why? Help?
[13:35:33 ERROR]: #!#! [Skript] Severe Error:
[13:35:33 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[13:35:33 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[13:35:33 ERROR]: #!#! and check whether this error has already been reported.
[13:35:33 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[13:35:33 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:35:33 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[13:35:33 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! Stack trace:
[13:35:33 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[13:35:33 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)
[13:35:33 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! Version Information:
[13:35:33 ERROR]: #!#!   Skript: 2.2-dev26f
[13:35:33 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[13:35:33 ERROR]: #!#!   Minecraft: 1.11.2
[13:35:33 ERROR]: #!#!   Java: 1.8.0_74 (Java HotSpot(TM) 64-Bit Server VM 25.74-b02)
[13:35:33 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! Running CraftBukkit: false
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! Current node: databases: (config.sk, line 177)
[13:35:33 ERROR]: #!#! Current item: null
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[13:35:33 ERROR]: #!#!
[13:35:33 ERROR]: #!#! End of Error.
[13:35:33 ERROR]: #!#!

**Comment by bensku** [comment] 2017-05-10 07:00
Did you use /reload?

**Comment by bensku** [comment] 2017-05-24 09:12
Anyway, duplicate of #237.

**Closed by bensku** 2017-05-24 09:12 UTC
