### ISSUE TITLE
cancel event doesn't work with "on Flow"

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#345] opened 2017-01-18 22:41 UTC
Using Spigot 1.10.2 and Skript dev23

`on flow:

    if event-world is "golf":
        if event-block is water:
            if "%block below the event-block%" contains "clay":
                cancel event`

This is the example that doesn't work (anymore). It used to work before, i had dev20 then i believe. I also tried removing all the conditions and other variations, cancel event just won't cut it here. However other effects do work, like i was able to get debug messages out of it etc.

No error messages were generated

**Comment by JeepSmash** [comment] 2017-01-19 09:27
I used the code that you have pasted here and the cancel event expression is working fine on dev23.  One thing you may want to note is that the event-block is NOT the block that is filling with water but the source block that will flow into an adjacent air block.  So your code will not allow any water to spread off of a clay block but will spread from other sources onto a clay block.  Not sure exactly what your intended operation is but i hope that helps.

**Comment by jaylawl** [comment] 2017-01-19 10:25
oh, i'll try  that out in a second. if that solves it there must have been some update, because as i explained the exact same code worked fine on dev20

thanks for the hint!

**Comment by jaylawl** [comment] 2017-01-20 21:14
well i messed around with this issue but im stumped as to what to do @JeepSmash 
would you be so kind to post an example of code that worked for you? i value your time and understand if you dont want to

**Comment by Pyon-Pyon** [comment] 2017-01-21 14:22
I cannot reproduce this at the 1.11.2 using the latest release with this code:
```
on flow:
	broadcast "World: %event-world%"
	if event-world is "world":
		broadcast "Next"
		broadcast "Block: %event-block%"
		if event-block is water:
			broadcast "Next"
			broadcast "below block: %block below event-block%"
			if block below event-block = any clay: #If you aren't using the latest version of the aliases (2.0.5) this may not work.
				broadcast "Next"
				cancel event
```

**Comment by jaylawl** [comment] 2017-01-21 15:20
well as i mentioned its on 1.10.2. also i copy pasted your exact code and got the same non-working result.

**Comment by jaylawl** [comment] 2017-01-21 20:14
so... i got this to work. by removing the condition "event-block" is water... Oo

not sure if im supposed to leave this issue open, it feels like a bug!

code im using now that works fine:
```
on flow:

    event-world is "golf"
    block below event-block = any clay
    cancel event
```

**Comment by jaylawl** [comment] 2017-01-21 20:30
so this issue was caused by comparing the event block to the wrong block type, which i originally discarded  over and over because the only thing that didnt work was the "cancel event" effect. is was comparing the event-block, which was flowing/moving water with stationary water. now, that would explain why cancelling the event had no effect - but it doesnt explain why other effects after the condition (that obviously had to fail somehow) still fired

**Comment by WheezyGold7931** [comment] 2017-08-25 15:38
@bensku title needs updating

**Comment by Snow-Pyon** [comment] 2018-01-07 07:51
User error, closing.

**Closed by Snow-Pyon** 2018-01-07 07:51 UTC
Labels: invalid
