### ISSUE TITLE
item check bug

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#883] opened 2017-09-22 09:25 UTC
test is an item
He added some nbt content

set {test} to book with nbt "{display:{Lore:[0:""§7test""],Name:""§r§r§btest""},Tags:[0:""_test_""]}"

Then I checked him in the function
function xbxy(p:player, s:string):
	if {_p}'s inventory has {test}:
		send "ok"
	else:
		send "no"
#Not detected

This writing can not detect it

But I use the following two wording can be detected

function xbxy(p:player, s:string):
	if {_p} is holding {test}:
		send "ok"
	else:
		send "no"
	#Can be detected
	
set {test::1} to book with nbt "{display:{Lore:[0:""§7test""],Name:""§r§r§btest""},Tags:[0:""_test_""]}"
function xbxy(p:player, s:string):
	loop {test::*}:
		if {_p}'s inventory has loop-value:
			send "ok"
		else:
			send "no"
	#Can be detected

Hope to repair

**Comment by bensku** [comment] 2017-09-22 11:11
Duplicate of #754.

**Closed by bensku** 2017-09-22 11:11 UTC
Labels: duplicate
