### ISSUE TITLE
Checking if a player is in a list not functioning

### ISSUE THREAD

**Issue by StealWonders** [bensku/Skript#1000] opened 2017-12-04 20:41 UTC
The follow code to check if a list contains a player is not working as intended:

`if {giveaway::*} contains player:` or `if player is in {giveaway::*}:`

Using skript dev32b

**Comment by Pikachu920** [comment] 2017-12-04 20:58
This is actually a more generic issue, contains doesn't function right on lists

**Comment by bensku** [comment] 2017-12-04 21:05
Are players keys or values in the list?

**Comment by Pikachu920** [comment] 2017-12-04 23:06
Or as skript calls thems, indexes or values

**Comment by Louis-D** [comment] 2017-12-05 19:51
I never got a skript manual or handbook for syntax naming but this is how I add the players:
`add player to {giveaway::*}`

**Comment by TheBentoBox** [comment] 2017-12-07 15:53
Just FYI @StealWonders, a "index" or "key" is the the named value that goes behind the `::` in a list variable by which the "value" you add is referenced. So if I add `add "example" to {list::*}`, the value `example` will be stored at index `1` of the list (and I could reference it specifically with `{list::1}`). If you put something specific behind the `::` then that custom thing you enter becomes in the key/index for your value (`set {lastLogin::%player%} to now`, the player is the index and `now` is the value).

With that out of the way, as @Pikachu920 said this is a more generic issue with the `contains` condition essentially working at all, which means this is a duplicate of #411, so I'm closing it. Feel free to provide more discussion or info over there, as it's set as a milestone issue for the 2.3 release.

**Closed by TheBentoBox** 2017-12-07 15:53 UTC
