### ISSUE TITLE
Aliases for IDs 438, 441 _are_ defined, but skript reports they are are not.

### ISSUE THREAD

**Issue by JadedDragoon** [bensku/Skript#397] opened 2017-02-22 14:55 UTC
I receive the following warning when reloading aliases:

```
>skript reload aliases
[09:17:38 INFO]: [Skript] Reloading the aliases...
[09:17:39 INFO]: Loaded a total of 19996 english aliases
[09:17:39 WARN]: There are no aliases defined for the following ids: 438, 441
[09:17:39 INFO]: [Skript] Successfully reloaded the aliases.
```

[This is my aliases file](http://pastebin.com/tmMArHdT)

As you can see not only are aliases for these item ids defined in the default section (which I have not edited) but I attempted to define them in the custom section as well.  The message persists both during startup and on reloading aliases.

The alias for potions (item id 373) does not seem to have this problem, despite not being defined differently and despite having similar game mechanics.

Spigot git-Spigot-65a0347-a552117 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
Skript v2.2-dev24b

**Comment by FUZIK** [comment] 2017-02-22 15:15
https://github.com/tim740/skAliases
https://github.com/tim740/skAliasesVerCheck/releases

**Comment by JadedDragoon** [comment] 2017-02-24 23:42
```
>skript reload aliases
[18:36:48 INFO]: [Skript] Reloading the aliases...
[18:36:48 INFO]: Loaded a total of 20487 english aliases
[18:36:48 WARN]: There are no aliases defined for the following ids: 438, 441
[18:36:48 INFO]: [Skript] Successfully reloaded the aliases.
```

As I said, the file I was already using had the ids defined. I thought I was very clear on that. I even provided the file as proof. As the new file has no differences where these ids are concerned it, predictably, has no effect on the problem. Please don't treat me as joe-nub-can't-operate-his-'putter. It just wastes everyone's time.

Regardless I'm now using the version 2.0.5 alias file from the above link, unedited. Same problem.

**Comment by TheBentoBox** [comment] 2017-02-25 02:36
I can confirm, this has been an issue since 1.9 dropped. I believe it's due to the way potions are parsed now, given that they're an expression instead of identified via something you can mark with aliases (an ID:data combo).

**Comment by SlimeDog** [comment] 2017-03-04 17:01
Duplicate of #275/

**Comment by TheBentoBox** [comment] 2017-03-04 17:28
True enough. See #275.

**Closed by TheBentoBox** 2017-03-04 17:28 UTC
Labels: aliases-rework, bug
