### ISSUE TITLE
Removing "List is missing 'and' or 'or', defaulting to 'and'"

### ISSUE THREAD

**Issue by Remixful** [bensku/Skript#495] opened 2017-04-12 23:10 UTC
I have a function with two number parameters and Skript thinks that I'm trying to make a list or something.
`set {_progresspercent} to getPercent(1,100)`

I then receive this warning.
`12.04 19:09:02 [Server] WARN List is missing 'and' or 'or', defaulting to 'and': 1,100 (experiment.sk, line 51: set {_progresspercent} to getPercent(1,100)')`
How am I supposed to disable this annoying message? Or at least how do I avoid it?

How to reproduce:
````
function test(a:number, b:number):
    stop

on load:
    test(1,2)
````

**Comment by Snow-Pyon** [comment] 2017-04-13 00:24
Could you show us the script where you declare such function? Never had this issue, so it could be an issue of how you're declaring the function.

**Comment by Remixful** [comment] 2017-04-13 02:20
@Snow-Pyon 
`function getPercent(current:number, max:number) :: number:
    set {_percent} to floor((100/ {_max} ) * {_current})
    return clamp({_percent}, 0, 100)`

**Comment by TheBentoBox** [comment] 2017-04-14 14:44
Confirmed.

**Comment by bensku** [comment] 2017-04-15 09:28
Hmm, would be interesting to find out why it happens for this function - usually it definitely doesn't appear.

**Comment by bensku** [comment] 2017-05-10 13:48
Apparently Skript was creating sub-parser since parameters were numbers. Anyway, fixed in next release.

**Closed** 2017-05-10 18:49 UTC
Labels: bug
