### ISSUE TITLE
citizens npc

### ISSUE THREAD

**Issue by yyeerai** [bensku/Skript#270] opened 2016-12-04 13:40 UTC
When click the citizens NPCS to send the information

    [21:35:47 INFO]: lapin_boy issued server command: /heal
    [21:36:50 INFO]: [Skript] 1
    [21:36:50 INFO]: [Skript] sign_post, wall_sign or sign_item
    [21:36:50 INFO]: [Skript] Got to the end
    [21:36:50 INFO]: [Skript] 1
    [21:36:50 INFO]: [Skript] null
    [21:36:51 INFO]: [Skript] 1
    [21:36:51 INFO]: [Skript] sign_post, wall_sign or sign_item
    [21:36:51 INFO]: [Skript] Got to the end

**Comment by Weefle** [comment] 2016-12-04 13:53
I have the same type of error when I rightclick on any entity who isn't the target.
Here the script: http://hastebin.com/gicedeboko.pas
And here the error: http://hastebin.com/woyeneqaso.md
That spam the logs!

**Comment by Pyon-Pyon** [comment] 2016-12-04 14:25
duplicate of https://github.com/bensku/Skript/issues/265#issuecomment-264701202

**Comment by Weefle** [comment] 2016-12-04 14:27
It isn't the same error!

**Comment by Pyon-Pyon** [comment] 2016-12-04 14:29
that are debug messages as I can see anyways.

**Comment by Weefle** [comment] 2016-12-04 14:35
ok xD

**Comment by bensku** [comment] 2016-12-05 09:47
When you click Citizen NPC? Uhh, I guess there is something wrong, not just debug messages.

**Closed** 2016-12-05 11:05 UTC
Labels: bug
