### ISSUE TITLE
Some creatures not detected in spawn event

### ISSUE THREAD

**Issue by Guarmanda** [bensku/Skript#550] opened 2017-05-08 15:59 UTC
Spawning bat, ghast, slime, magma cube, or squid won't be detected by the "on spawn" event, and can't be canceled

**Comment by skripttpbug2** [comment] 2017-05-09 08:03
[Doesn't seem like this is the case](https://i.imgur.com/dta3Vvm.png)

**Comment by Syst3ms** [comment] 2017-05-09 10:53
He isn't talking about the `spawn` effect, but rather about the `on spawn:` event

**Comment by Snow-Pyon** [comment] 2017-05-09 14:09
@Syst3ms he broadcasted the event-entity in the spawn event and that's why you can see a message  the spawned entity in the chat.

**Comment by TheBentoBox** [comment] 2017-05-09 17:11
Cannot reproduce personally, to close unless someone else can confirm,

**Comment by TheBentoBox** [comment] 2017-05-09 18:08
Actually, I CAN reproduce this, just not using the same code @skripttpbug2 used. I assume they did something like this:

```
on spawn:
    broadcast "%event-entity%"
```

And that _does_ work fine. However, creating specific event listeners for the spawning of the particular creatures listed in this suggestion do not parse correctly, here's an example script:

```
on spawn of bat:
	broadcast "%event-entity%"
on spawn of ghast:
	broadcast "%event-entity%"
on spawn of slime:
	broadcast "%event-entity%"
on spawn of magma cube :
	broadcast "%event-entity%"
on spawn of squid:
	broadcast "%event-entity%"
on spawn of zombie:
	broadcast "%event-entity%"
```

and here are the resulting errors:

![image](https://cloud.githubusercontent.com/assets/6902229/25865457/f02d1f8a-34c0-11e7-8bc5-9e0584e47667.png)

As you can see, the only one that loads properly is the zombie listener, the rest break even though they shoudn't.

**Comment by bensku** [comment] 2017-05-10 13:38
Error message is correct, technically. For Bukkit plugins, bats and some other animals are not *creatures* - which is stupid. Easy to fix, luckily.

**Comment by TheBentoBox** [comment] 2017-05-11 22:29
This is fixed in dev27.

**Closed by TheBentoBox** 2017-05-11 22:29 UTC
Labels: bug

**Comment by Guarmanda** [comment] 2017-05-12 22:51
No it's not. Just tested it.
