### ISSUE TITLE
Play event is not working , Latest skript version.

### ISSUE THREAD

**Issue by MoneyAlpha** [bensku/Skript#1084] opened 2018-01-29 12:15 UTC
[15:09:11] [Server thread/INFO]: MoneyAlpha issued server command: /sk reload ArsaFly
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:09:11] [Server thread/ERROR]: #!#! Could not load ArsaFly.sk
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[15:09:11] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:09:11] [Server thread/ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[15:09:11] [Server thread/ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[15:09:11] [Server thread/ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[15:09:11] [Server thread/ERROR]: #!#! nor it will work, unless you switch to supported platform.
[15:09:11] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Stack trace:
[15:09:11] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for visualeffect
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1788)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1755)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1503)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1476)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional$1.<init>(Conditional.java:72)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:72)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:978)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:450)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[15:09:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[15:09:11] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:09:11] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[15:09:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:09:11] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:09:11] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:09:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:09:11] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Version Information:
[15:09:11] [Server thread/ERROR]: #!#!   Skript: 2.2-dev32d (latest)
[15:09:11] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:09:11] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[15:09:11] [Server thread/ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) Client VM 25.151-b12)
[15:09:11] [Server thread/ERROR]: #!#!   OS: Windows 7 x86 6.1
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[15:09:11] [Server thread/ERROR]: #!#! Running Spigot (or compatible): true
[15:09:11] [Server thread/ERROR]: #!#! Running Paper (or compatible): true
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Current node: play raw sound "mob.bat.death" at player with pitch 1 volume 10 (ArsaFly.sk, line 11)
[15:09:11] [Server thread/ERROR]: #!#! Current item: null
[15:09:11] [Server thread/ERROR]: #!#! Thread: Server thread
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! Language: english
[15:09:11] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[15:09:11] [Server thread/ERROR]: #!#! 
[15:09:11] [Server thread/ERROR]: #!#! End of Error.
[15:09:11] [Server thread/ERROR]: #!#!

**Comment by Snow-Pyon** [comment] 2018-01-29 12:17
Duplicate of #1076.

**Closed by Snow-Pyon** 2018-01-29 12:17 UTC
