### ISSUE TITLE
Not a valid item data

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1251] opened 2018-05-11 17:19 UTC
Error when reloading this script:
https://i.imgur.com/gte1fDL.png

```
				set {_statusitem} to RED WOOL BLOCK

			make a gui slot 10 of {_p} with {_statusitem} with name "&4Event Status" with lore "&7Status: %{_eventstatus}%||&9Öffne oder schliesse das Event" to run function Setting_Status(10,{_id},{_p}) using "left" click
```

Latest release of benskus fork.

seems to have something to do with the set variable {_statusitem} and RED WOOL BLOCK. Because when I write this, no error occurs:

`			make a gui slot 10 of {_p} with RED WOOL BLOCK with name "&4Event Status" with lore "&7Status: %{_eventstatus}%||&9Öffne oder schliesse das Event" to run function Setting_Status(10,{_id},{_p}) using "left" click
`

**Comment by HYPExMon5ter** [comment] 2018-05-11 19:59
Duplicate of #1138

**Comment by TheBentoBox** [comment] 2018-05-11 20:00
Thank you @HYPExMon5ter

**Closed** 2018-05-11 20:00 UTC
Labels: duplicate

**Comment by HYPExMon5ter** [comment] 2018-05-11 20:02
No problem (:
