### ISSUE TITLE
error on server stop

### ISSUE THREAD

**Issue by mat41997** [bensku/Skript#580] opened 2017-05-21 13:44 UTC
logs
https://gist.github.com/mat41997/d4cb401c90357689f53b7b28d9e760c0

timings
https://timings.aikar.co/?id=0c7d1f4a4fa44cb3aeccc1851897a588

torch
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

**Comment by bensku** [comment] 2017-05-24 09:12
Duplicate of #237

**Closed by bensku** 2017-05-24 09:12 UTC
Labels: duplicate
