### ISSUE TITLE
Default values for text-based function arguments can be set to anything.

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#452] opened 2017-03-29 23:49 UTC
The following functions have unquoted text-based arguments and they all parse without error.
```javascript
function brokenArgs(first: text = anything at all!):
    broadcast "%{_first}%"
```
Unlike the previous function, however, this one will throw an exception when called:
```javascript
function brokenArgs(multi: texts = I can type anything I want):
    broadcast {_multi::*}
```
Nothing is thrown when they're combined:
```javascript
function brokenArgs(first: text = hi there, multi: texts = why hello):
    broadcast "%{_first}% %{_multi::*}%"
```
Not sure if this is intended behavior, but it makes for some *interesting* function declarations, to say the least:

```javascript
function wat(first: text, stuff: texts = (what: booleans = (why: objects = (how: boolean = true)))):
    broadcast "%{_first}% %{_stuff::*}%"
```

Using:
* Skript version 2.2-dev25
*  CraftBukkit version git-Spigot-b4417b8-a552117 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by TheBentoBox** [comment] 2017-03-31 01:56
Good lord that final function declaration.

This definitely sounds like a bug; does the third one work as intended? You say nothing is thrown, but does the default value for the `multi` texts argument get sent in and work properly?

**Comment by RezzedUp** [comment] 2017-03-31 04:11
> You say nothing is thrown, but does the default value for the multi texts argument get sent in and work properly?

Yes, the value that both `first` and `multi` are broadcasted.

`wat("first-value")` broadcasts `first-value (what: booleans = (why: objects = (how: boolean = true)))`

**Comment by bensku** [comment] 2017-04-03 09:35
Case 1: I have added a warning about unquoted strings which contain spaces. However, it is feature; stupid one, but still one which has been there for a long time.

Case 2: Uhh, this is strange one. Will not be fixed for next release.

Case 3: Will give a warning like case 1 does.

**Comment by Snow-Pyon** [comment] 2018-01-07 08:09
Fixed in dev26b.

**Closed by Snow-Pyon** 2018-01-07 08:09 UTC
Labels: bug
