### ISSUE TITLE
Error with latest Skript dev18c

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#150] opened 2016-08-01 13:34 UTC
http://hastebin.com/apovuliduy.vbs

**Comment by JKGamerxD** [comment] 2016-08-01 14:37
That is a bug with the updater, simply disable the option `check new version` in the `config.sk`

**Comment by bensku** [comment] 2016-08-01 15:04
Updater server seems to be down. Will fix by writing my own updater for next release, but for now you can toggle it off.

**Comment by bensku** [comment] 2016-08-01 15:06
Duplicate of #146.

**Closed by bensku** 2016-08-01 15:06 UTC
