### ISSUE TITLE
on command bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#978] opened 2017-11-20 03:56 UTC
Skript version: dev32
Spigot version: 1.12.2

```
on command:
	broadcast "%complete command%"
```
when using the code above, it will only broadcast commands that **aren't** skript commands, so if I do /skript reload all, it'd broadcast, but say I have a command /test, that I coded in skript, it would not broadcast anything.

**Comment by Snow-Pyon** [comment] 2017-11-20 08:46
Well, if you look at the docs, it says the following:
>Called when a player enters a command (not neccessarily a Skript command). 

So, it might be an intended behavior. And using the on command event with Skript commands seems kinda pointless for me so, I see no problem with it working in that way.

**Comment by HYPExMon5ter** [comment] 2017-11-20 16:30
I was using it for a command spy, it used to work fine.

**Comment by Pikachu920** [comment] 2017-11-21 23:24
@Snow-Pyon that sentence implies that it's called for all commands (including Skript commands). The part in parenthesis just clarifies it goes off for more than Skript commands.

**Comment by melinstagibson** [comment] 2017-11-22 04:38
noticed that aswell.

sure, you technically wont need it for skript commands but that makes things just more complicated. 
i mean its "on command" and not "on most commands"

**Comment by TheBentoBox** [comment] 2017-11-22 14:35
Yeah, this should definitely also be called for Skript commands. I'll mark it as a bug for now, but I won't be able to attempt reproduction any time soon, so if someone else could verify when they get the chance that'd be helpful!

**Comment by Snow-Pyon** [comment] 2017-11-22 15:44
I couldn't reproduce it on PaperSpigot 1.12.2 with Skript dev32b.

**Comment by HYPExMon5ter** [comment] 2017-11-22 17:39
https://gfycat.com/EveryTimelyAmericanredsquirrel
code:
```
on command:
	broadcast "&aOn command: &7%full command%"
```

**Comment by RiverThrough** [comment] 2017-11-23 23:35
Just thought I'd drop by and say that I was not able to replicate this either, i'm on:
Skript version: dev32b
Spigot version: 1.12.2
Could this be an addon affecting the functionality?

**Comment by HYPExMon5ter** [comment] 2017-11-23 23:37
I mean, it’s possible, but idk. Want me to list my addons?

**Comment by TheBentoBox** [comment] 2017-11-24 02:12
Even if it's caused by an addon, it should be reported to that addon's developer, not here, so I'll be closing this.

How are you registering your commands, out of curiosity? You're not detecting them via another "on command" event, right?

**Closed by TheBentoBox** 2017-11-24 02:12 UTC
Labels: bug

**Comment by HYPExMon5ter** [comment] 2017-11-24 02:45
No why would I do that? Lmao.
```
command /acommand:
    trigger:
        send “blah”
```
That’s how I code commands, how they’re supposed to be coded.

**Comment by TheBentoBox** [comment] 2017-11-24 04:51
Because some people make that mistake and I was making sure you weren't. Just being safe :)

Try to see if it's caused by an addon and contact the developer if you find the cause, but yeah, seems to be an issue on your end since nobody else is experiencing this.

**Comment by HYPExMon5ter** [comment] 2017-11-24 05:15
Alright, I’ll try to do some testing.

**Comment by TheBentoBox** [comment] 2017-11-24 05:20
Good luck! If you or anyone finds a way to reproduce with vanilla Skript I'm happy to reopen.

**Comment by HYPExMon5ter** [comment] 2017-11-24 06:10
Actually nvm, still not fixed, onto removing addons now

**Comment by HYPExMon5ter** [comment] 2017-11-24 06:49
https://gfycat.com/NearWelcomeIvorybackedwoodswallow
removed literally all plugin, except skript and disabled all scripts except the one I was using to test (it just has a command /test and the on command in it) and still didn't work, tried switching to dev25, and still doesn't work so idk 😨

**Comment by RiverThrough** [comment] 2017-11-25 01:12
@HYPExMon5ter the best way to figure out if its something on your end or not is to start up a fresh server locally and try it like that, there may be a setting somewhere causing this and finding it will be a pain in the ass so before you even start looking for it make sure a fresh new server with skript and whatnot does not replicate the error
