### ISSUE TITLE
Vector issue

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1050] opened 2018-01-09 13:06 UTC
Using latest Skript version, PaperSpigot 1.12.2

I get this error:
https://i.imgur.com/IrmtkTK.png

This is the script:
```
command /rad2:
	trigger:
		set {_loc} to location of player
		subtract 0.5 from y-coord of {_loc}
		set {_loc2} to location of block 3 blocks in front of player
		set {_direction} to vector between {_loc} and {_loc2}

```

**Comment by TheBentoBox** [comment] 2018-01-09 13:21
Looks to me like a duplicate of #828, at some point using the word 'blocks' in a direction expression broke. Try changing it to `3 meters in front of player`, or just `3 in front of player`. Also, a small nitpick that doesn't matter too much, but you should strive for accurate report titles since really this issue has nothing to do with vectors (the part causing the error isn't the one line that deals with vectors). Again, not a big deal, but just to avoid being misleading.

I'll close this since like I said this seems like #828 but I can reopen if that turns out not to be the case.

**Closed by TheBentoBox** 2018-01-09 13:21 UTC
