### ISSUE TITLE
Skript cannot understand the direction

### ISSUE THREAD

**Issue by simonchow96** [bensku/Skript#1021] opened 2017-12-18 12:23 UTC
I have a code like this:
`on rightclick on sign: 
             set 1 block horizontally to the right of the clicked block to redstone block`

And Script has returned me the error:

`[20:23:28 ERROR]: Can't understand this condition/effect: set 1 block horizontally to the right of the clicked block to redstone block (test.sk, line 2: set 1 block horizontally to the right of the clicked block to redstone block')`

What shall I do?

**Comment by Blueyescat** [comment] 2017-12-18 13:40
Hmm, the code should be incorrect, but what is _horizontally_ right of a block? lol
You can just use **``set block right of clicked block to redstone block``**

**Comment by simonchow96** [comment] 2017-12-18 13:58
So... what shall I do if I want to write:
`set block 2 blocks below the block 1 blocks behind the block 3 blocks right clicked block to redstone block`

It keeps saying error...

**Comment by simonchow96** [comment] 2017-12-18 14:07
So when I try the dev29, the parsing issue disappear, but it can't recognise "[heavy/light ]weighted pressure plate" in the code on the Minecraft 1.12.2. It runs perfectly on Minecraft 1.11.2 with no bug.

**Comment by simonchow96** [comment] 2017-12-18 14:49
So... what shall I do if I want to write:
set block 2 blocks below the block 1 blocks behind the block 3 blocks right clicked block to redstone block

It keeps saying error in dev32c, while it runs perfectly with the code in dev29 with no bug.

**Comment by JeepSmash** [comment] 2017-12-25 05:09
i noticed alot of directions no longer work by using the word "block" or "blocks" as a distance.  Use "meter" or "meters" instead and it should fix alot of the direction issues that worked in previous versions but not the latest.  This most likely boils down to a change in the aliases or language files where block or blocks are not parsing as a measure of distance sometimes (my guess).

**Comment by TheBentoBox** [comment] 2018-01-02 03:48
This looks to be a duplicate of #828 to me.

**Closed by TheBentoBox** 2018-01-02 03:48 UTC
