### ISSUE TITLE
Play Sound Doesn't Work

### ISSUE THREAD

**Issue by Techno3600** [bensku/Skript#1057] opened 2018-01-12 21:15 UTC
Here is the error:

https://pastebin.com/raw/FSERzV28

I've already checked with Skellet and they have denied the error being their fault.

**Comment by Pikachu920** [comment] 2018-01-13 03:48
Duplicate of #876

**Closed** 2018-01-13 09:33 UTC

**Comment by Techno3600** [comment] 2018-01-13 20:07
That looks nothing like a duplicate, I am using the very latest version released a few days ago, it still doesn’t work.

**Comment by Pikachu920** [comment] 2018-01-13 20:29
look at the stack traces, its probably the same root issue
