### ISSUE TITLE
Event 'every 30 minecraft minutes in world:' not working

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#857] opened 2017-09-07 09:35 UTC
The time checking events seem to be off, especially this one:
```
every 30 minecraft minutes in "Survival5":
	broadcast "&cDebug: &fStage 1 Pass"
```
It simply doesn't broadcast it, no error in console either.

Skript dev31b and Spigot 1.12.1

**Comment by Nicofisi** [comment] 2017-10-05 07:04
Had it worked before or did you try it for the first time before reporting?

**Comment by whoshenry** [comment] 2017-10-05 07:28
First time trying it.

**Comment by Nicofisi** [comment] 2018-02-22 13:19
Duplicate of #464, I discussed it in #464

**Closed** 2018-02-22 13:52 UTC
Labels: bug, priority: lowest
