### ISSUE TITLE
on click

### ISSUE THREAD

**Issue by kiritss** [bensku/Skript#469] opened 2017-04-07 16:26 UTC
with latest update skript cannot understand the condition

on click with paper:

Cannot compare block with "a sign"

and else needing to be after if or else if even if they are both there.

**Comment by bensku** [comment] 2017-04-07 16:41
Cannot reproduce. What are your Skript and Spigot versions? What is your Minecraft version?

If you have addons, please try removing them one by one to see if the issue disappears with some of them.

**Comment by kiritss** [comment] 2017-04-07 16:51
Not sure why it's happening, I thought it would be addons so I've tried to update every single one I had. I'm using latest paperspigot & skript. Issue started when I updated skript

**Comment by kiritss** [comment] 2017-04-07 17:01
Okay, at this point i've removed every single addons and the problem is still persisting. Pretty much all the conditions do not work

**Comment by kiritss** [comment] 2017-04-07 17:23
Is it possible for it to stop working if i deleted english alias so it would regenerate (and it never did)

**Comment by kiritss** [comment] 2017-04-07 17:37
Alright seemingly it was, but are color codes no longer supported in skript?

**Comment by TheBentoBox** [comment] 2017-04-07 18:19
That's an issue caused by the new JSON chat feature as is being discussed in #465. As you seem to have figured out your issue here, I'll close this.

**Closed by TheBentoBox** 2017-04-07 18:19 UTC
