### ISSUE TITLE
Error with functions and numbers

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#586] opened 2017-05-23 10:47 UTC
Skript v2.2-dev25
git-Paper-1081 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

I have this issue:
https://forums.skunity.com/threads/skript-bug-with-functions.3775/

**Comment by Snow-Pyon** [comment] 2017-05-23 11:26
Duplicate of #495, this was fixed on the dev27.

**Closed** 2017-05-23 20:18 UTC
