### ISSUE TITLE
Block/location at dropped item returns last skript dropped item's values

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#1139] opened 2018-03-05 15:20 UTC
```
on drop:
	wait 1 second
	broadcast "%location of block at dropped item%"
	broadcast "%block at dropped item%"
```
The code above always returns same block type and coordinates no matter where the drop happens. I have tried multiple ways but haven't found a solution to get the correct location/block type at the dropped item.

**Comment by Nicofisi** [comment] 2018-03-05 15:32
The same block type and coordinates, which are..?

**Comment by AsDsDD** [comment] 2018-03-05 15:42
![2018-03-05_17 37 52](https://user-images.githubusercontent.com/19997813/36983803-fb171a0a-209b-11e8-95ee-cf5a8d684d03.png)
Those values in the photo above. Sometimes I get other values but I haven't still figured out what causes them to change... Odd

**Comment by TheBentoBox** [comment] 2018-03-05 15:49
Possibly unrelated but I had a REALLY weird issue a couple of months ago that this reminds me of; I was trying to check the block in a block break event and it would sometimes randomly return the location of a log or leaf block at a seemingly random location in the world. Sometimes when I'd tp to the cords of the block it returned, there was a fire there, which got me wondering if it was returning locations of blocks that were burned or decayed (in the case of leaves) instead of the actual event location.

This was on my live server where I had tons of plugins and addons installed so it's by no means guaranteed to have been a Skript issue but I just felt it was worth mentioning since this issue is reminiscent of that one.

**Comment by Nicofisi** [comment] 2018-03-05 15:50
@AsDsDD and in your case, when you TP to those location, is there anything here?

**Comment by Nicofisi** [comment] 2018-03-05 15:53
Also, does the `wait 1 second` change something (/is it needed) or is it in your example for no specific reason? 🤔

**Comment by AsDsDD** [comment] 2018-03-05 15:56
Yeah, when teleporting to that location it takes me inside a jungle tree. The wait 1 second is to let the item fall so it wouldn't give the throwing player's location but rather the fallen item's location

**Comment by AsDsDD** [comment] 2018-03-05 15:59
No, it doesn't give correct location either way

**Comment by AsDsDD** [comment] 2018-03-05 16:42
Okay, I figured the logic how skript gives those values. The values are the last item's dropped by skript 
Eg. skript dropping things (drop 3 gravel for example) > you get the gravel drop's values next time player drops something

**Comment by Nicofisi** [comment] 2018-03-05 19:01
Hmm I wonder what it returns after a restart when nothing was dropped yet and how (whether at all) that relates to @TheBentoBox's issue, an interesting thing is going on here for sure xD

**Comment by Pikachu920** [comment] 2018-03-05 20:25
`dropped item` isn't meant to return the dropped item. There's event-entity for that.

**Comment by Nicofisi** [comment] 2018-03-05 20:43
@Pikachu920 but is it an intended behavior that this returns the last dropped item with Skript or should it perhaps error or something?

**Comment by Pikachu920** [comment] 2018-03-06 00:29
yes that is also intended. last spawned entity works the same way

**Comment by TheBentoBox** [comment] 2018-03-06 02:58
It is kinda weird but I do think Pika is correct, if you look at the `last spawned entity` expression [here](http://bensku.github.io/Skript/expressions#ExprLastSpawnedEntity), which includes the last dropped item, you'll see that the [last] part means it's optional, i.e. `last dropped item` is the same expression as `dropped item`. In the drop event, the item hasn't been dropped yet, so the `last dropped item` will be the one from the previous drop event.

That being said, I'm not going to close this until we get more confirmation from a dev (@Snow-Pyon ?) since it is somewhat confusing.

**Comment by Snow-Pyon** [comment] 2018-03-06 03:54
Tested and confirmed that was the issue, use event-entity or `the item` the next time.

**Closed by Snow-Pyon** 2018-03-06 03:54 UTC
